<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Domain\ZosyalMedya.Modules.Questions.Domain.csproj" />
    <ProjectReference Include="..\..\Profiles\Contracts\ZosyalMedya.Modules.Profiles.Contracts.csproj" />
    <ProjectReference Include="..\..\Search\Contracts\ZosyalMedya.Modules.Search.Contracts.csproj" />
    <ProjectReference Include="..\..\SocialGraph\Contracts\ZosyalMedya.Modules.SocialGraph.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Application\ZosyalMedya.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
