import { ChangeDetectionStrategy,Component,effect,OnDestroy,OnInit,signal,untracked } from '@angular/core';
import { ActivatedRoute,RouterLink } from '@angular/router';
import { acceptFollow,Api,block,follow,getProfileByHandle,getRelationship,getSocialGraphSummary,listIncomingFollowRequests,listSocialGraphProfiles,mute,rejectFollow,RelationshipView,SearchHit,SocialGraphProfileView,SocialGraphSummaryView,unblock,unfollow,unmute } from '@platform/api';
import { IonButton,IonChip,IonContent,IonHeader,IonItem,IonLabel,IonList,IonNote,IonTitle,IonToolbar } from '@ionic/angular/standalone';
import { Subscription } from 'rxjs';
import { MobileSession } from '../../core/auth/secure-token-storage';
import { MobileProfilePickerComponent } from '../../shared/mobile-profile-picker.component';

type GraphKind='Followers'|'Following'|'Requests';

@Component({
  selector:'app-mobile-connections',
  imports:[RouterLink,IonButton,IonChip,IonContent,IonHeader,IonItem,IonLabel,IonList,IonNote,IonTitle,IonToolbar,MobileProfilePickerComponent],
  template:`<ion-header translucent="true"><ion-toolbar><ion-title>Bağlantılar</ion-title></ion-toolbar></ion-header><ion-content [fullscreen]="true">
    <div class="page-intro"><p>SOSYAL AĞ</p><h1>Bağlantıların.</h1><span>Takipçilerini, takip ettiklerini ve bekleyen isteklerini gerçek hesaplardan yönet.</span></div>
    <section class="graph" aria-labelledby="graph-title"><h2 id="graph-title">Sosyal ağ</h2>
      @if(graphLoading()&&!summary()){<p class="graph-state" aria-busy="true">Bağlantılar yükleniyor…</p>}
      @else if(graphError()&&!summary()){<p class="graph-state" role="alert">Bağlantılar yüklenemedi. <button type="button" (click)="reloadGraph()">Tekrar dene</button></p>}
      @else if(summary();as value){<nav class="graph-tabs" aria-label="Bağlantı listeleri">
        <button type="button" [class.active]="graphKind()==='Followers'" (click)="selectGraph('Followers')"><strong>{{value.followerCount}}</strong><span>Takipçi</span></button>
        <button type="button" [class.active]="graphKind()==='Following'" (click)="selectGraph('Following')"><strong>{{value.followingCount}}</strong><span>Takip</span></button>
        @if(value.canManageRequests){<button type="button" [class.active]="graphKind()==='Requests'" (click)="selectGraph('Requests')"><strong>{{value.pendingRequestCount}}</strong><span>İstek</span></button>}
      </nav>
      @if(graphLoading()&&!people().length){<p class="graph-state" aria-busy="true">Liste yükleniyor…</p>}@else if(graphError()&&!people().length){<p class="graph-state" role="alert">Liste yüklenemedi. <button type="button" (click)="loadGraphList(true)">Tekrar dene</button></p>}@else{
        <ion-list inset="true">@for(person of people();track person.ownerId){<ion-item lines="full"><span class="avatar" slot="start" aria-hidden="true">{{initials(person.displayName)}}</span><ion-label><a [routerLink]="['/profil',person.handle]"><h2>{{person.displayName}}</h2><p>&#64;{{person.handle}}</p></a></ion-label>@if(graphKind()==='Requests'){<div class="request-actions" slot="end"><ion-button size="small" [disabled]="actingId()===person.ownerId" (click)="decide(person,true)">Kabul</ion-button><ion-button size="small" fill="clear" [disabled]="actingId()===person.ownerId" (click)="decide(person,false)">Reddet</ion-button></div>}</ion-item>}@empty{<ion-item><ion-label>{{graphKind()==='Requests'?'Bekleyen takip isteğin yok.':graphKind()==='Followers'?'Görünür takipçi yok.':'Görünür takip edilen profil yok.'}}</ion-label></ion-item>}</ion-list>}
      @if(graphNextCursor()){<ion-button expand="block" fill="outline" [disabled]="graphLoading()" (click)="loadGraphList(false)">Daha fazla</ion-button>}}
    </section>
    <section class="relationship-tools" aria-labelledby="relationship-title"><div class="page-intro compact"><p>İLİŞKİ KONTROLÜ</p><h2 id="relationship-title">Bir bağlantıyı yönet.</h2><span>Profil adıyla ara; kimlik kodu paylaşman gerekmez.</span></div>
      <zm-mobile-profile-picker label="Profil seç" hint="Takip, sessize alma veya engelleme durumunu görmek istediğin kişiyi ara." (selectedChange)="selectTarget($event)"/>
      <ion-button class="save" expand="block" (click)="inspect()" [disabled]="!target()||pending()">{{pending()?'İnceleniyor…':'İncele'}}</ion-button>
      @if(message()){<ion-note class="status" role="status">{{message()}}</ion-note>}@if(state();as relation){<ion-list inset="true"><ion-item><ion-label><p>{{target()?.title}} ile takip durumu</p><h2>{{followStateLabel(relation.followState)}}</h2></ion-label><ion-chip>{{relation.isBlocked||relation.isBlockedByTarget?'Engelli':'Açık'}}</ion-chip></ion-item><ion-item><ion-label>Sessize alındı</ion-label><strong>{{relation.isMuted?'Evet':'Hayır'}}</strong></ion-item><ion-item><ion-label>Yakın çevre</ion-label><strong>{{relation.isCloseFriend?'Evet':'Hayır'}}</strong></ion-item></ion-list><div class="action-grid"><ion-button (click)="act('follow')" [disabled]="pending()">Takip et</ion-button><ion-button fill="outline" (click)="act('unfollow')" [disabled]="pending()">Takibi bırak</ion-button><ion-button fill="outline" (click)="act(relation.isMuted?'unmute':'mute')" [disabled]="pending()">{{relation.isMuted?'Sesi aç':'Sessize al'}}</ion-button><ion-button color="danger" fill="clear" (click)="act(relation.isBlocked?'unblock':'block')" [disabled]="pending()">{{relation.isBlocked?'Engeli kaldır':'Engelle'}}</ion-button></div>}
    </section>
  </ion-content>`,
  styles:[`.graph{padding:0 1rem 1rem}.graph>h2{margin:.25rem .25rem .7rem;font:700 1.5rem/1.1 Georgia,serif}.graph-tabs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.4rem}.graph-tabs button{min-height:56px;border:1px solid var(--ion-border-color);border-radius:.75rem;background:var(--ion-item-background);color:var(--ion-text-color)}.graph-tabs button.active{border-color:var(--ion-color-primary);box-shadow:inset 0 0 0 1px var(--ion-color-primary)}.graph-tabs strong,.graph-tabs span{display:block}.graph-tabs span{font-size:.68rem;color:var(--ion-color-medium)}.graph-state{padding:.8rem;color:var(--ion-color-medium)}.graph-state button{min-height:44px;border:0;background:transparent;color:var(--ion-color-primary);font-weight:750}.avatar{display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:var(--ion-color-primary);color:var(--ion-color-primary-contrast);font-weight:800}.request-actions{display:flex;flex-direction:column}.relationship-tools{border-top:1px solid var(--ion-border-color)}.page-intro.compact{padding-top:1.5rem}.page-intro.compact h2{font:700 2rem/1 Georgia,serif;margin:.3rem 0}@media(max-width:360px){.graph-tabs{grid-template-columns:1fr}.request-actions{align-items:stretch}}`],
  changeDetection:ChangeDetectionStrategy.OnPush
})
export class MobileConnectionsPage implements OnInit,OnDestroy{
  readonly target=signal<SearchHit|null>(null);readonly state=signal<RelationshipView|null>(null);readonly message=signal('');readonly pending=signal(false);
  readonly summary=signal<SocialGraphSummaryView|null>(null);readonly graphKind=signal<GraphKind>('Followers');readonly people=signal<SocialGraphProfileView[]>([]);readonly graphNextCursor=signal<string|null>(null);readonly graphLoading=signal(false);readonly graphError=signal(false);readonly actingId=signal<string|null>(null);
  private ownerId='';private explicitHandle='';private routeReady=false;private graphRevision=0;private listRevision=0;private routeSubscription?:Subscription;private readonly syncSession=effect(()=>{const subject=this.session.subject();untracked(()=>{if(!this.routeReady||this.explicitHandle)return;const kind=this.graphKind();const revision=++this.graphRevision;++this.listRevision;this.resetGraph(kind);this.ownerId=subject??'';if(subject)void this.loadGraph(kind,revision);else{this.graphLoading.set(false);this.graphError.set(false);}});});
  constructor(private readonly api:Api,private readonly route:ActivatedRoute,private readonly session:MobileSession){}
  ngOnInit():void{this.routeSubscription=this.route.queryParamMap.subscribe(params=>{const revision=++this.graphRevision;++this.listRevision;const view=this.parseKind(params.get('view'));const handle=params.get('profil')?.trim()??'';this.routeReady=true;this.explicitHandle=handle;this.resetGraph(view);if(handle)void this.resolveOwner(handle,view,revision);else{this.ownerId=this.session.subject()??'';if(this.ownerId)void this.loadGraph(view,revision);else this.graphLoading.set(false);}});}
  ngOnDestroy():void{this.routeSubscription?.unsubscribe();++this.graphRevision;++this.listRevision;}
  reloadGraph():void{void this.loadGraph(this.graphKind(),++this.graphRevision);}
  selectGraph(kind:GraphKind):void{if(kind==='Requests'&&!this.summary()?.canManageRequests)return;this.graphKind.set(kind);void this.loadGraphList(true);}
  async loadGraphList(reset:boolean,revision=this.graphRevision):Promise<void>{if(!this.ownerId||(!reset&&this.graphLoading()))return;const listRevision=reset?++this.listRevision:this.listRevision;const kind=this.graphKind();const cursor=reset?undefined:this.graphNextCursor()??undefined;this.graphLoading.set(true);this.graphError.set(false);try{const page=kind==='Requests'?await this.api.invoke(listIncomingFollowRequests,{limit:20,cursor}):await this.api.invoke(listSocialGraphProfiles,{ownerId:this.ownerId,kind,limit:20,cursor});if(revision!==this.graphRevision||listRevision!==this.listRevision||kind!==this.graphKind())return;this.people.update(current=>reset?page.items:[...current,...page.items.filter(person=>!current.some(item=>item.ownerId===person.ownerId))]);this.graphNextCursor.set(page.nextCursor??null);}catch{if(revision===this.graphRevision&&listRevision===this.listRevision)this.graphError.set(true);}finally{if(revision===this.graphRevision&&listRevision===this.listRevision)this.graphLoading.set(false);}}
  async decide(person:SocialGraphProfileView,accept:boolean):Promise<void>{if(this.actingId()||this.graphKind()!=='Requests'||!this.summary()?.canManageRequests)return;const revision=this.graphRevision;this.actingId.set(person.ownerId);try{await this.api.invoke(accept?acceptFollow:rejectFollow,{requesterId:person.ownerId});if(revision!==this.graphRevision)return;this.people.update(items=>items.filter(item=>item.ownerId!==person.ownerId));this.summary.update(value=>value?{...value,followerCount:value.followerCount+(accept?1:0),pendingRequestCount:Math.max(0,value.pendingRequestCount-1)}:value);this.message.set(accept?'Takip isteği kabul edildi.':'Takip isteği reddedildi.');}catch{if(revision===this.graphRevision)this.message.set('Takip isteği güncellenemedi.');}finally{if(revision===this.graphRevision)this.actingId.set(null);}}
  selectTarget(profile:SearchHit|null):void{this.target.set(profile);this.state.set(null);this.message.set('');}
  async inspect():Promise<void>{const target=this.target();if(!target||this.pending())return;this.pending.set(true);try{this.state.set(await this.api.invoke(getRelationship,{targetId:target.ownerId}));this.message.set('');}catch{this.state.set(null);this.message.set('İlişki bilgisi alınamadı. Bağlantını kontrol edip tekrar dene.');}finally{this.pending.set(false);}}
  async act(action:'follow'|'unfollow'|'mute'|'unmute'|'block'|'unblock'):Promise<void>{const target=this.target();if(!target||this.pending())return;const fn={follow,unfollow,mute,unmute,block,unblock}[action];this.pending.set(true);try{this.state.set(await this.api.invoke(fn,{targetId:target.ownerId}));this.message.set('Durum güncellendi.');}catch{this.message.set('İşlem ilişki politikası nedeniyle uygulanamadı.');}finally{this.pending.set(false);}}
  followStateLabel(state:RelationshipView['followState']):string{return{None:'Takip edilmiyor',Pending:'İstek bekliyor',Following:'Takip ediliyor'}[state];}
  initials(name:string):string{return name.trim().split(/\s+/).slice(0,2).map(word=>word[0]?.toLocaleUpperCase('tr-TR')??'').join('')||'K';}
  private async resolveOwner(handle:string,kind:GraphKind,revision:number):Promise<void>{try{const profile=await this.api.invoke(getProfileByHandle,{handle});if(revision!==this.graphRevision)return;this.ownerId=profile.ownerId;await this.loadGraph(kind,revision);}catch{if(revision===this.graphRevision){this.graphLoading.set(false);this.graphError.set(true);}}}
  private async loadGraph(kind:GraphKind,revision=this.graphRevision):Promise<void>{if(!this.ownerId){this.graphLoading.set(false);this.graphError.set(true);return;}this.graphLoading.set(true);this.graphError.set(false);try{const summary=await this.api.invoke(getSocialGraphSummary,{ownerId:this.ownerId});if(revision!==this.graphRevision)return;this.summary.set(summary);this.graphKind.set(kind==='Requests'&&summary.canManageRequests?'Requests':kind==='Following'?'Following':'Followers');await this.loadGraphList(true,revision);}catch{if(revision===this.graphRevision){this.graphLoading.set(false);this.graphError.set(true);}}}
  private resetGraph(kind:GraphKind):void{this.ownerId='';this.summary.set(null);this.graphKind.set(kind);this.people.set([]);this.graphNextCursor.set(null);this.graphLoading.set(true);this.graphError.set(false);this.actingId.set(null);}
  private parseKind(value:string|null):GraphKind{return value?.toLowerCase()==='requests'?'Requests':value?.toLowerCase()==='following'?'Following':'Followers';}
}
