import { ChangeDetectionStrategy,Component,OnDestroy,effect,signal,untracked } from '@angular/core';
import { FormControl,FormGroup,ReactiveFormsModule,Validators } from '@angular/forms';
import { Api,getMyProfile,ProfileView,updateMyProfile } from '@platform/api';
import { IonButton,IonContent,IonHeader,IonInput,IonItem,IonList,IonNote,IonSpinner,IonTitle,IonToggle,IonToolbar } from '@ionic/angular/standalone';
import { MobileAuthorizedMediaGalleryComponent } from '../../core/media/mobile-authorized-media-gallery.component';
import { MobileSession } from '../../core/auth/secure-token-storage';

const PROFILE_CACHE='escp:mobile:public-profile:v2';
@Component({selector:'app-mobile-profile',imports:[ReactiveFormsModule,IonButton,IonContent,IonHeader,IonInput,IonItem,IonList,IonNote,IonSpinner,IonTitle,IonToggle,IonToolbar,MobileAuthorizedMediaGalleryComponent],template:`<ion-header translucent="true"><ion-toolbar><ion-title>Profil</ion-title></ion-toolbar></ion-header><ion-content [fullscreen]="true"><div class="page-intro"><p>GÖRÜNÜR KİMLİK</p><h1>Kendini nasıl anlatıyorsun?</h1><span>{{profile()?.completenessPercentage??25}}% tamamlandı</span></div>@if(profile()?.coverMediaId;as cover){<zm-mobile-authorized-media-gallery [mediaIds]="[cover]" label="Profil kapak görseli" />}@if(profile()?.profileMediaId;as avatar){<zm-mobile-authorized-media-gallery [mediaIds]="[avatar]" label="Profil fotoğrafı" />}<form [formGroup]="form" (ngSubmit)="save()"><ion-list inset="true"><ion-item><ion-input label="Kullanıcı adı" labelPlacement="stacked" formControlName="handle"></ion-input></ion-item><ion-item><ion-input label="Görünen ad" labelPlacement="stacked" formControlName="displayName"></ion-input></ion-item><ion-item><ion-input label="Biyografi" labelPlacement="stacked" formControlName="biography"></ion-input></ion-item><ion-item><ion-input label="Konum" labelPlacement="stacked" formControlName="location"></ion-input></ion-item><ion-item><ion-toggle formControlName="isPrivate">Özel profil</ion-toggle></ion-item><ion-item><ion-toggle formControlName="reduceMotion">Hareketi azalt</ion-toggle></ion-item></ion-list>@if(message()){<ion-note class="status" [color]="saved()?'success':'medium'">{{message()}}</ion-note>}<ion-button class="save" expand="block" type="submit" [disabled]="form.invalid||saving()">@if(saving()){<ion-spinner name="crescent"></ion-spinner>}@else{Değişiklikleri kaydet}</ion-button></form></ion-content>`,changeDetection:ChangeDetectionStrategy.OnPush})
export class MobileProfilePage implements OnDestroy{
  readonly profile=signal<ProfileView|null>(null);readonly saving=signal(false);readonly saved=signal(false);readonly message=signal('');
  readonly form=new FormGroup({handle:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(3)]}),displayName:new FormControl('',{nonNullable:true,validators:[Validators.required]}),biography:new FormControl('',{nonNullable:true}),location:new FormControl('',{nonNullable:true}),isPrivate:new FormControl(false,{nonNullable:true}),reduceMotion:new FormControl(false,{nonNullable:true})});
  private revision=0;private readonly sync=effect(()=>{const subject=this.session.subject();untracked(()=>{void this.load(subject);});});
  constructor(private readonly api:Api,private readonly session:MobileSession){}
  ngOnDestroy():void{this.revision++;this.sync.destroy();}
  private async load(subject:string|null):Promise<void>{const revision=++this.revision;this.profile.set(null);this.form.reset({handle:'',displayName:'',biography:'',location:'',isPrivate:false,reduceMotion:false});this.saving.set(false);this.saved.set(false);this.message.set('');if(!subject)return;const cacheKey=`${PROFILE_CACHE}:${subject}`;let cached=false;try{const value=localStorage.getItem(cacheKey);if(value){this.apply(JSON.parse(value) as ProfileView);cached=true;}}catch{/* Network data remains authoritative. */}try{const profile=await this.api.invoke(getMyProfile);if(revision!==this.revision||subject!==this.session.subject())return;this.apply(profile);localStorage.setItem(cacheKey,JSON.stringify(profile));}catch{if(revision===this.revision&&subject===this.session.subject())this.message.set(cached?'Çevrimdışısın; son kaydedilen profil gösteriliyor.':'Profilini ilk kez oluşturabilirsin.');}}
  private apply(profile:ProfileView):void{this.profile.set(profile);this.form.patchValue({handle:profile.handle,displayName:profile.displayName,biography:profile.biography??'',location:profile.location??'',isPrivate:profile.isPrivate,reduceMotion:profile.reduceMotion});}
  async save():Promise<void>{if(this.form.invalid)return;const revision=this.revision;const subject=this.session.subject();if(!subject)return;this.saving.set(true);this.saved.set(false);try{const value=this.form.getRawValue();const current=this.profile();const profile=await this.api.invoke(updateMyProfile,{body:{...value,organization:current?.organization??null,websiteUrl:current?.websiteUrl??null,profileMediaId:current?.profileMediaId??null,coverMediaId:current?.coverMediaId??null,theme:current?.theme??'System',language:current?.language??'Turkish'}});if(revision!==this.revision||subject!==this.session.subject())return;this.apply(profile);localStorage.setItem(`${PROFILE_CACHE}:${subject}`,JSON.stringify(profile));this.message.set('Profil güncellendi.');this.saved.set(true);}catch{if(revision===this.revision&&subject===this.session.subject())this.message.set('Değişiklikler kaydedilemedi. Bağlantını kontrol et.');}finally{if(revision===this.revision)this.saving.set(false);}}
}
