<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="..\Domain\ZosyalMedya.Modules.Communities.Domain.csproj" /><ProjectReference Include="..\Contracts\ZosyalMedya.Modules.Communities.Contracts.csproj" /><ProjectReference Include="..\..\..\BuildingBlocks\Application\ZosyalMedya.BuildingBlocks.Application.csproj" /><ProjectReference Include="..\..\Profiles\Contracts\ZosyalMedya.Modules.Profiles.Contracts.csproj" /><ProjectReference Include="..\..\Search\Contracts\ZosyalMedya.Modules.Search.Contracts.csproj" /></ItemGroup></Project>
