// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZosyalMedya.Modules.Communities.Infrastructure.Persistence;

#nullable disable

namespace ZosyalMedya.Modules.Communities.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommunitiesDbContext))]
    [Migration("20260712081632_InitialCommunities")]
    partial class InitialCommunities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("communities")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZosyalMedya.Modules.Communities.Domain.Communities.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<List<Guid>>("_pinnedContentIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("PinnedContentIds");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status", "Visibility", "UpdatedAtUtc");

                    b.ToTable("communities", "communities");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Communities.Domain.Communities.Community", b =>
                {
                    b.OwnsMany("ZosyalMedya.Modules.Communities.Domain.Communities.CommunityAuditEntry", "_audit", b1 =>
                        {
                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Sequence")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Sequence"));

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("ActorId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("OccurredAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("CommunityId", "Sequence");

                            b1.ToTable("audit", "communities");

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");
                        });

                    b.OwnsMany("ZosyalMedya.Modules.Communities.Domain.Communities.CommunityMember", "_members", b1 =>
                        {
                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<DateTimeOffset>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CommunityId", "UserId");

                            b1.HasIndex("UserId", "Status");

                            b1.ToTable("members", "communities");

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");
                        });

                    b.OwnsMany("ZosyalMedya.Modules.Communities.Domain.Communities.CommunityRule", "_rules", b1 =>
                        {
                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Order")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Order"));

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.HasKey("CommunityId", "Order");

                            b1.ToTable("rules", "communities");

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");
                        });

                    b.Navigation("_audit");

                    b.Navigation("_members");

                    b.Navigation("_rules");
                });
#pragma warning restore 612, 618
        }
    }
}
