import { ChangeDetectionStrategy,Component,effect,OnDestroy,OnInit,signal,viewChild } from '@angular/core';
import { FormControl,FormGroup,ReactiveFormsModule,Validators } from '@angular/forms';
import { ActivatedRoute,RouterLink } from '@angular/router';
import { Api,answerQuestion,archiveQuestion,askQuestion,deleteQuestion,getProfileByHandle,getQuestionInbox,ProfileView,QuestionView,SearchHit } from '@platform/api';
import { IonButton,IonContent,IonHeader,IonInput,IonItem,IonLabel,IonList,IonNote,IonSelect,IonSelectOption,IonTextarea,IonTitle,IonToggle,IonToolbar } from '@ionic/angular/standalone';
import { MobileProfilePickerComponent } from '../../shared/mobile-profile-picker.component';
import { Subscription } from 'rxjs';

@Component({selector:'app-mobile-questions',imports:[ReactiveFormsModule,RouterLink,IonButton,IonContent,IonHeader,IonInput,IonItem,IonLabel,IonList,IonNote,IonSelect,IonSelectOption,IonTextarea,IonTitle,IonToggle,IonToolbar,MobileProfilePickerComponent],template:`<ion-header translucent="true"><ion-toolbar><ion-title>Sorular</ion-title></ion-toolbar></ion-header><ion-content [fullscreen]="true"><div class="page-intro"><p>SORU ALANI</p><h1>Gelen kutun.</h1><span>Anonim kimlik normal yanıtta gösterilmez.</span></div><zm-mobile-profile-picker label="Soruyu göndereceğin profili seç" hint="Ad veya kullanıcı adıyla gerçek bir profil ara." (selectedChange)="selectTarget($event)"></zm-mobile-profile-picker><form [formGroup]="form" (ngSubmit)="ask()"><ion-list inset="true"><ion-item><ion-textarea label="Sorun" labelPlacement="stacked" formControlName="body" [autoGrow]="true" maxlength="1000"></ion-textarea></ion-item><ion-item><ion-select label="Yanıtın görünürlüğü" labelPlacement="stacked" formControlName="audience"><ion-select-option value="Profile">Yalnız profil sahibi</ion-select-option><ion-select-option value="Followers">Takipçiler</ion-select-option><ion-select-option value="Public">Herkese açık</ion-select-option></ion-select></ion-item><ion-item><ion-toggle formControlName="isAnonymous">Anonim gönder</ion-toggle></ion-item></ion-list><ion-button class="save" expand="block" type="submit" [disabled]="form.invalid||!target()||sending()">{{sending()?'Gönderiliyor…':'Soruyu gönder'}}</ion-button></form>@if(message()){<ion-note class="status" role="status">{{message()}}</ion-note>}<ion-list inset="true">@for(question of questions();track question.id){<ion-item lines="full"><ion-label class="ion-text-wrap"><p>{{question.status}} · {{question.audience}} · {{question.isAnonymous?'Anonim':'Tanımlı'}}</p><h2>{{question.body}}</h2>@if(question.answer){<p>{{question.answer}}</p><a [routerLink]="['/sorular',question.id]">Yanıtı aç</a>}@if(question.status==='Published'){<ion-input #answerText placeholder="Yanıt yaz"></ion-input><ion-button (click)="answer(question,answerText.value?.toString()??'')">Yanıtla</ion-button>}<ion-button fill="clear" color="medium" (click)="archive(question)" [disabled]="deletingId()===question.id">Arşivle</ion-button>@if(confirmingDeleteId()===question.id){<p role="group" aria-label="Soruyu silme onayı">Soru ve yanıt gizlensin mi? <ion-button fill="clear" (click)="confirmingDeleteId.set(null)">Vazgeç</ion-button><ion-button color="danger" (click)="remove(question)" [disabled]="deletingId()===question.id">Evet, sil</ion-button></p>}@else{<ion-button fill="clear" color="danger" (click)="confirmingDeleteId.set(question.id)">Sil</ion-button>}</ion-label></ion-item>}@empty{<ion-item><ion-label>Henüz soru yok.</ion-label></ion-item>}</ion-list></ion-content>`,changeDetection:ChangeDetectionStrategy.OnPush})
export class MobileQuestionsPage implements OnInit,OnDestroy{
  readonly questions=signal<QuestionView[]>([]);readonly message=signal('');readonly target=signal<SearchHit|null>(null);readonly sending=signal(false);readonly confirmingDeleteId=signal<string|null>(null);readonly deletingId=signal<string|null>(null);readonly profilePicker=viewChild(MobileProfilePickerComponent);private readonly syncRouteTarget=effect(()=>{const target=this.target();const picker=this.profilePicker();if(target&&picker)picker.choose(target);});private loadRevision=0;private profileRevision=0;private routeSubscription?:Subscription;
  readonly form=new FormGroup({body:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(4)]}),audience:new FormControl<'Profile'|'Followers'|'Public'>('Profile',{nonNullable:true}),isAnonymous:new FormControl(true,{nonNullable:true})});
  constructor(private readonly api:Api,private readonly route:ActivatedRoute){}ngOnInit():void{void this.load();this.routeSubscription=this.route.queryParamMap.subscribe(params=>{const revision=++this.profileRevision;const handle=params.get('profil')?.trim()??'';this.target.set(null);this.profilePicker()?.clear();if(handle)void this.preselect(handle,revision);});}ngOnDestroy():void{this.routeSubscription?.unsubscribe();++this.profileRevision;}
  async load():Promise<void>{const revision=++this.loadRevision;try{const items=await this.api.invoke(getQuestionInbox,{limit:50});if(revision===this.loadRevision)this.questions.set(items);}catch{if(revision===this.loadRevision)this.message.set('Sorular yüklenemedi.');}}
  selectTarget(profile:SearchHit|null):void{this.target.set(profile);this.message.set('');}
  async ask():Promise<void>{const target=this.target();if(this.form.invalid||!target||this.sending())return;this.sending.set(true);try{const value=this.form.getRawValue();await this.api.invoke(askQuestion,{body:{...value,targetId:target.ownerId,isDraft:false,publishAtUtc:null}});this.form.controls.body.reset();this.message.set('Soru gönderildi.');}catch{this.message.set('Soru gönderilemedi. Profilin soru izinlerini kontrol edebilirsin.');}finally{this.sending.set(false);}}
  async answer(question:QuestionView,text:string):Promise<void>{if(!text.trim())return;const before=this.questions();this.questions.update(items=>items.map(item=>item.id===question.id?{...item,status:'Answered',answer:text}:item));try{const updated=await this.api.invoke(answerQuestion,{id:question.id,body:{answer:text}});this.questions.update(items=>items.map(item=>item.id===updated.id?updated:item));}catch{this.questions.set(before);this.message.set('Yanıt kaydedilemedi.');}}
  async archive(question:QuestionView):Promise<void>{try{const updated=await this.api.invoke(archiveQuestion,{id:question.id});this.questions.update(items=>items.map(item=>item.id===updated.id?updated:item));}catch{this.message.set('Arşivleme başarısız.');}}
  async remove(question:QuestionView):Promise<void>{if(this.deletingId())return;++this.loadRevision;this.deletingId.set(question.id);try{await this.api.invoke(deleteQuestion,{id:question.id});this.questions.update(items=>items.filter(item=>item.id!==question.id));this.confirmingDeleteId.set(null);this.message.set('Soru silindi.');}catch{this.message.set('Soru silinemedi.');}finally{this.deletingId.set(null);}}
  private async preselect(handle:string,revision:number):Promise<void>{try{const profile=await this.api.invoke(getProfileByHandle,{handle});if(revision!==this.profileRevision)return;this.target.set(this.profileHit(profile));}catch{if(revision===this.profileRevision)this.message.set('Bağlantıdaki profil seçilemedi; başka bir profil arayabilirsin.');}}
  private profileHit(profile:ProfileView):SearchHit{return{id:profile.id,ownerId:profile.ownerId,type:'Profile',title:profile.displayName,snippet:`@${profile.handle}`,deepLink:`/profil/${profile.handle}`,matchedTags:[],score:1};}
}
