using Microsoft.EntityFrameworkCore;
using MongoDB.Driver;
using ZosyalMedya.BuildingBlocks.Application.Persistence;
using ZosyalMedya.Modules.Questions.Application.Ports;
using ZosyalMedya.Modules.Questions.Application.Questions;
using ZosyalMedya.Modules.Questions.Domain.Questions;
using ZosyalMedya.Modules.Questions.Infrastructure.Persistence.MongoDb;
using ZosyalMedya.Modules.Questions.Infrastructure.Persistence.PostgreSql;
using ZosyalMedya.Modules.Profiles.Contracts;
using ZosyalMedya.Modules.SocialGraph.Contracts;
using Xunit;

namespace ZosyalMedya.Tests.Integration.Persistence;
public abstract class QuestionRepositoryContractTests
{
    protected abstract Task<IQuestionRepository> CreateRepositoryAsync();
    [Fact] public async Task CreateSelectSortConcurrencyAndDeleteBehaveEqually() { if (!InfrastructureTestGate.IsEnabled) return; var repository = await CreateRepositoryAsync(); var now = new DateTimeOffset(2026, 7, 12, 8, 0, 0, TimeSpan.Zero); var target = new QuestionUserId(Guid.NewGuid()); var question = Question.Create(QuestionId.New(), new(Guid.NewGuid()), target, "Sağlayıcı sözleşmesi sorusu", true, QuestionAudience.Profile, false, null, now); await repository.CreateAsync(question); Assert.NotNull(await repository.SelectAsync(x => x.Id == question.Id)); Assert.Single(await repository.ListByFilterAsync(x => x.TargetId == target, new QueryOptions<Question>(10, [new(x => x.CreatedAtUtc, ZosyalMedya.BuildingBlocks.Application.Persistence.SortDirection.Descending)]))); var version = question.Version; question.Answer(target, "Sözleşme yanıtı", now.AddMinutes(1)); Assert.True(await repository.UpdateAsync(x => x.Id == question.Id, question, version)); Assert.False(await repository.UpdateAsync(x => x.Id == question.Id, question, version)); await Assert.ThrowsAsync<PersistenceConflictException>(() => repository.CreateAsync(question)); Assert.Equal(1, await repository.DeleteByFilterAsync(x => x.Id == question.Id)); }
    [Fact] public async Task DueScheduledQueryIsDeterministic() { if (!InfrastructureTestGate.IsEnabled) return; var repository = await CreateRepositoryAsync(); var now = new DateTimeOffset(2026, 7, 12, 9, 0, 0, TimeSpan.Zero); var question = Question.Create(QuestionId.New(), new(Guid.NewGuid()), new(Guid.NewGuid()), "Zamanlanmış sağlayıcı sorusu", false, QuestionAudience.Public, false, now.AddMinutes(5), now); await repository.CreateAsync(question); var due = await repository.ListDueScheduledAsync(now.AddMinutes(6), 10); Assert.Contains(due, item => item.Id == question.Id); Assert.Equal(due.OrderBy(item => item.PublishAtUtc).ThenBy(item => item.Id).Select(item => item.Id), due.Select(item => item.Id)); await repository.DeleteByFilterAsync(x => x.Id == question.Id); }
    [Fact] public async Task DetailReadEnforcesAudienceAndNeverLeaksAnonymousSender() { if (!InfrastructureTestGate.IsEnabled) return; var repository = await CreateRepositoryAsync(); var now = new DateTimeOffset(2026, 8, 13, 8, 0, 0, TimeSpan.Zero); var target = new QuestionUserId(Guid.NewGuid()); var stranger = new QuestionUserId(Guid.NewGuid()); var question = Question.Create(QuestionId.New(), new(Guid.NewGuid()), target, "Anonim ayrıntı sorusu", true, QuestionAudience.Profile, false, null, now); question.Answer(target, "Güvenli ayrıntı yanıtı", now.AddMinutes(1)); await repository.CreateAsync(question); var handler = new GetQuestionHandler(repository,new ProfilesStub(),new GraphStub(false)); Assert.False((await handler.HandleAsync(question.Id, stranger, default)).IsSuccess); var ownerView = await handler.HandleAsync(question.Id, target, default); Assert.True(ownerView.IsSuccess); Assert.Null(ownerView.Value!.SenderId); Assert.Null(ownerView.Value.Sender); await repository.DeleteByFilterAsync(x => x.Id == question.Id); }
    [Fact] public async Task FollowersAudienceAllowsOnlyRealUnblockedFollowerAndOpenSenderHasIdentity() { if (!InfrastructureTestGate.IsEnabled) return; var repository = await CreateRepositoryAsync(); var now = new DateTimeOffset(2026, 8, 13, 9, 0, 0, TimeSpan.Zero); var sender = new QuestionUserId(Guid.NewGuid()); var target = new QuestionUserId(Guid.NewGuid()); var follower = new QuestionUserId(Guid.NewGuid()); var question = Question.Create(QuestionId.New(),sender,target,"Takipçilere açık soru",false,QuestionAudience.Followers,false,null,now); question.Answer(target,"Takipçilere açık yanıt",now.AddMinutes(1)); await repository.CreateAsync(question); var profiles=new ProfilesStub(new(sender.Value,"acik_gonderen","Açık Gönderen",false,null,false)); var allowed=await new GetQuestionHandler(repository,profiles,new GraphStub(true)).HandleAsync(question.Id,follower,default); Assert.True(allowed.IsSuccess); Assert.Equal("acik_gonderen",allowed.Value!.Sender!.Handle); var denied=await new GetQuestionHandler(repository,profiles,new GraphStub(false)).HandleAsync(question.Id,follower,default); Assert.False(denied.IsSuccess); await repository.DeleteByFilterAsync(x=>x.Id==question.Id); }
    private sealed class ProfilesStub(ProfileLookup? profile=null):IProfilesModule { public Task<ProfileLookup?> FindByOwnerIdAsync(Guid ownerId,CancellationToken cancellationToken=default)=>Task.FromResult(profile?.OwnerId==ownerId?profile:null); public Task<IReadOnlyDictionary<Guid,ProfileLookup>> FindByOwnerIdsAsync(IReadOnlySet<Guid> ownerIds,CancellationToken cancellationToken=default)=>Task.FromResult<IReadOnlyDictionary<Guid,ProfileLookup>>(profile is not null&&ownerIds.Contains(profile.OwnerId)?new Dictionary<Guid,ProfileLookup>{{profile.OwnerId,profile}}:new Dictionary<Guid,ProfileLookup>()); }
    private sealed class GraphStub(bool following):ISocialGraphModule { public Task<RelationshipLookup> GetAsync(Guid actorId,Guid targetId,CancellationToken cancellationToken=default)=>Task.FromResult(new RelationshipLookup(actorId,targetId,following,false,false,false,false)); public Task<IReadOnlySet<Guid>> ListFollowingIdsAsync(Guid actorId,CancellationToken cancellationToken=default)=>Task.FromResult<IReadOnlySet<Guid>>(new HashSet<Guid>()); }
}
public sealed class PostgreSqlQuestionRepositoryContractTests : QuestionRepositoryContractTests
{
    protected override async Task<IQuestionRepository> CreateRepositoryAsync() { var db = new QuestionsDbContext(new DbContextOptionsBuilder<QuestionsDbContext>().UseNpgsql("Host=localhost;Port=55432;Database=zosyalmedya;Username=zosyalmedya;Password=local_only_change_me").Options); await db.Database.MigrateAsync(); return new PostgreSqlQuestionRepository(db); }
}
public sealed class MongoQuestionRepositoryContractTests : QuestionRepositoryContractTests
{
    protected override async Task<IQuestionRepository> CreateRepositoryAsync() { var repository = new MongoQuestionRepository(new MongoClient("mongodb://localhost:57017").GetDatabase("zosyalmedya_contract_tests")); await repository.EnsureIndexesAsync(CancellationToken.None); return repository; }
}
