using Microsoft.Extensions.DependencyInjection;using Microsoft.Extensions.Hosting;using Microsoft.Extensions.Logging;using ZosyalMedya.BuildingBlocks.Domain;using ZosyalMedya.Modules.Notifications.Application.Ports;using ZosyalMedya.Modules.Notifications.Domain.Inbox;
namespace ZosyalMedya.Modules.Notifications.Infrastructure.Delivery;
public sealed class NotificationDeliveryException(string message,Exception?inner=null):Exception(message,inner);
public sealed class LocalNotificationChannel(ILogger<LocalNotificationChannel>logger):INotificationChannel
{private static readonly Action<ILogger,Guid,string,Exception?>LogDelivery=LoggerMessage.Define<Guid,string>(LogLevel.Information,new EventId(4201,"LocalNotificationDelivered"),"Local notification {NotificationId} delivered with template {Template}");public Task DeliverAsync(Notification notification,CancellationToken cancellationToken=default){LogDelivery(logger,notification.Id.Value,$"{notification.TitleTemplateKey}:v{notification.TemplateVersion}",null);return Task.CompletedTask;}}
public sealed class NotificationDeliveryWorker(IServiceProvider provider,TimeProvider timeProvider,ILogger<NotificationDeliveryWorker>logger):BackgroundService
{
 private static readonly Action<ILogger,Exception?>LogCycleFailed=LoggerMessage.Define(LogLevel.Error,new EventId(4303,"NotificationDeliveryCycleFailed"),"Notification delivery cycle failed; the next cycle will retry");
 protected override async Task ExecuteAsync(CancellationToken stoppingToken){using var timer=new PeriodicTimer(TimeSpan.FromSeconds(5),timeProvider);while(!stoppingToken.IsCancellationRequested){try{if(!await timer.WaitForNextTickAsync(stoppingToken))break;await using var scope=provider.CreateAsyncScope();var repository=scope.ServiceProvider.GetRequiredService<INotificationRepository>();var channels=scope.ServiceProvider.GetServices<INotificationChannel>().ToArray();var now=timeProvider.GetUtcNow();foreach(var item in await repository.ListDueDeliveriesAsync(now,50,stoppingToken)){var version=item.Version;try{foreach(var channel in channels)await channel.DeliverAsync(item,stoppingToken);item.MarkDelivered(now);}catch(NotificationDeliveryException exception){var delay=TimeSpan.FromSeconds(Math.Pow(2,item.DeliveryAttempts+1)*5);item.ScheduleRetry(exception.Message,now+delay,now);}await repository.UpdateAsync(x=>x.Id==item.Id,item,version,stoppingToken);}}catch(OperationCanceledException)when(stoppingToken.IsCancellationRequested){break;}catch(Exception exception){LogCycleFailed(logger,exception);}}}
}
