// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZosyalMedya.Modules.Content.Infrastructure.Persistence.PostgreSql;

#nullable disable

namespace ZosyalMedya.Modules.Content.Infrastructure.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260712064844_InitialContent")]
    partial class InitialContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Domain.Posts.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentWarning")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid[]>("MediaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string[]>("Mentions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("OriginalPostId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShareKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("OriginalPostId");

                    b.HasIndex("AuthorId", "Status", "PublishedAtUtc");

                    b.HasIndex("Status", "Visibility", "PublishedAtUtc");

                    b.ToTable("posts", "content");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Domain.Posts.Post", b =>
                {
                    b.OwnsMany("ZosyalMedya.Modules.Content.Domain.Posts.PostRevision", "_revisions", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Revision")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Revision"));

                            b1.Property<string>("ContentWarning")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)");

                            b1.Property<DateTimeOffset>("EditedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LinkUrl")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("character varying(5000)");

                            b1.HasKey("PostId", "Revision");

                            b1.ToTable("post_revisions", "content");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("_revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
