// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZosyalMedya.Modules.Content.Infrastructure.Persistence.PostgreSql;

#nullable disable

namespace ZosyalMedya.Modules.Content.Infrastructure.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260712102119_AddPostImpressions")]
    partial class AddPostImpressions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZosyalMedya.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "DeadLetteredAtUtc", "NextAttemptAtUtc", "LockedUntilUtc");

                    b.ToTable("outbox", "integration", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Domain.Polls.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMultiple")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClosesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClosesAtUtc");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("polls", "content");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Domain.Posts.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentWarning")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid[]>("MediaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string[]>("Mentions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("OriginalPostId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShareKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("OriginalPostId");

                    b.HasIndex("AuthorId", "Status", "PublishedAtUtc");

                    b.HasIndex("Status", "Visibility", "PublishedAtUtc");

                    b.ToTable("posts", "content");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Domain.Saved.SavedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("OwnerId", "Collection", "CreatedAtUtc");

                    b.HasIndex("OwnerId", "PostId", "Collection")
                        .IsUnique();

                    b.ToTable("saved_content", "content");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Infrastructure.Persistence.PostgreSql.PollBallot", b =>
                {
                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CastAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid[]>("OptionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("PollId", "ActorId");

                    b.ToTable("poll_ballots", "content");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Infrastructure.Persistence.PostgreSql.PostImpression", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViewerHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("UtcDay")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PostId", "ViewerHash", "UtcDay");

                    b.ToTable("post_impressions", "content");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Domain.Polls.Poll", b =>
                {
                    b.HasOne("ZosyalMedya.Modules.Content.Domain.Posts.Post", null)
                        .WithOne()
                        .HasForeignKey("ZosyalMedya.Modules.Content.Domain.Polls.Poll", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ZosyalMedya.Modules.Content.Domain.Polls.PollOption", "_options", b1 =>
                        {
                            b1.Property<Guid>("PollId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<long>("VoteCount")
                                .HasColumnType("bigint");

                            b1.HasKey("PollId", "Id");

                            b1.ToTable("poll_options", "content");

                            b1.WithOwner()
                                .HasForeignKey("PollId");
                        });

                    b.Navigation("_options");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Domain.Posts.Post", b =>
                {
                    b.OwnsMany("ZosyalMedya.Modules.Content.Domain.Posts.PostRevision", "_revisions", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Revision")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Revision"));

                            b1.Property<string>("ContentWarning")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)");

                            b1.Property<DateTimeOffset>("EditedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LinkUrl")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("character varying(5000)");

                            b1.HasKey("PostId", "Revision");

                            b1.ToTable("post_revisions", "content");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("_revisions");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Domain.Saved.SavedContent", b =>
                {
                    b.HasOne("ZosyalMedya.Modules.Content.Domain.Posts.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Infrastructure.Persistence.PostgreSql.PollBallot", b =>
                {
                    b.HasOne("ZosyalMedya.Modules.Content.Domain.Polls.Poll", null)
                        .WithMany()
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Content.Infrastructure.Persistence.PostgreSql.PostImpression", b =>
                {
                    b.HasOne("ZosyalMedya.Modules.Content.Domain.Posts.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
