import { ChangeDetectionStrategy,Component,OnDestroy,OnInit,signal } from '@angular/core';
import { ActivatedRoute,RouterLink } from '@angular/router';
import { Api,FeedItem,getFeed,getProfileByHandle,getSocialGraphSummary,ProfileView,SocialGraphSummaryView } from '@platform/api';
import { IonBackButton,IonButton,IonButtons,IonContent,IonHeader,IonNote,IonTitle,IonToolbar } from '@ionic/angular/standalone';
import { MobileAuthorizedMediaGalleryComponent } from '../../core/media/mobile-authorized-media-gallery.component';
import { Subscription } from 'rxjs';
import { MobileStoryRailComponent } from '../stories/mobile-story-rail.component';

@Component({selector:'app-mobile-profile-detail',imports:[RouterLink,IonBackButton,IonButton,IonButtons,IonContent,IonHeader,IonNote,IonTitle,IonToolbar,MobileAuthorizedMediaGalleryComponent,MobileStoryRailComponent],template:`
<ion-header translucent="true"><ion-toolbar><ion-buttons slot="start"><ion-back-button defaultHref="/akis"></ion-back-button></ion-buttons><ion-title>Profil</ion-title></ion-toolbar></ion-header>
<ion-content [fullscreen]="true">@if(loading()){<section class="detail-state" aria-busy="true"><h1>Profil yükleniyor</h1></section>}@else if(error()){<section class="detail-state" role="alert"><h1>Profil açılamadı</h1><p>Profil kaldırılmış, gizlenmiş veya bağlantı kesilmiş olabilir.</p><ion-button (click)="load()">Tekrar dene</ion-button></section>}@else if(profile();as item){
@if(item.coverMediaId){<zm-mobile-authorized-media-gallery [mediaIds]="[item.coverMediaId]" label="Profil kapak görseli" />}
<header class="profile-head">@if(item.profileMediaId){<zm-mobile-authorized-media-gallery [mediaIds]="[item.profileMediaId]" label="Profil fotoğrafı" />}<p class="kicker">PROFİL</p><h1>{{item.displayName}}</h1><strong>&#64;{{item.handle}}</strong><p>{{item.biography||'Henüz biyografi eklenmedi.'}}</p><div class="meta">@if(item.location){<span>{{item.location}}</span>}@if(item.organization){<span>{{item.organization}}</span>}<span>{{item.isPrivate?'Özel profil':'Herkese açık profil'}}</span></div>@if(summary();as graph){<div class="actions graph-links"><a [routerLink]="['/baglantilar']" [queryParams]="{profil:item.handle,view:'followers'}"><strong>{{graph.followerCount}}</strong> takipçi</a><a [routerLink]="['/baglantilar']" [queryParams]="{profil:item.handle,view:'following'}"><strong>{{graph.followingCount}}</strong> takip</a></div>}<div class="actions"><a [routerLink]="['/sorular']" [queryParams]="{profil:item.handle}">Soru sor</a><a [routerLink]="['/mesajlar']" [queryParams]="{profil:item.handle}">Mesaj gönder</a></div></header><zm-mobile-story-rail [ownerId]="item.ownerId" [allowCreate]="false" />
<section class="timeline" aria-label="Profil gönderileri"><h2>Gönderiler</h2>@for(post of items();track post.content.id){<article><a [routerLink]="['/icerik',post.content.id]"><strong>{{post.content.text||'Medya paylaşımı'}}</strong></a>@if(post.content.mediaIds.length){<zm-mobile-authorized-media-gallery [mediaIds]="post.content.mediaIds" />}</article>}@empty{<ion-note>Görüntülenebilen gönderi yok.</ion-note>}@if(nextCursor()){<ion-button expand="block" fill="outline" [disabled]="loadingMore()" (click)="loadMore()">Daha eski paylaşımlar</ion-button>}</section>}
</ion-content>`,styleUrl:'./mobile-detail.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class MobileProfileDetailPage implements OnInit,OnDestroy{readonly profile=signal<ProfileView|null>(null);readonly summary=signal<SocialGraphSummaryView|null>(null);readonly items=signal<FeedItem[]>([]);readonly nextCursor=signal<string|null>(null);readonly loading=signal(true);readonly loadingMore=signal(false);readonly error=signal(false);private handle='';private revision=0;private subscription?:Subscription;constructor(private readonly api:Api,private readonly route:ActivatedRoute){}ngOnInit():void{this.subscription=this.route.paramMap.subscribe(params=>{this.handle=params.get('handle')??'';const revision=++this.revision;this.profile.set(null);this.summary.set(null);this.items.set([]);this.nextCursor.set(null);this.loadingMore.set(false);void this.load(revision);});}ngOnDestroy():void{this.subscription?.unsubscribe();++this.revision;}async load(revision=this.revision):Promise<void>{this.loading.set(true);this.error.set(false);try{const profile=await this.api.invoke(getProfileByHandle,{handle:this.handle});if(revision!==this.revision)return;this.profile.set(profile);const [feedResult,summaryResult]=await Promise.allSettled([this.api.invoke(getFeed,{kind:'Profile',profileId:profile.ownerId,limit:10,cursor:undefined}),this.api.invoke(getSocialGraphSummary,{ownerId:profile.ownerId})]);if(revision!==this.revision)return;if(feedResult.status==='fulfilled'){this.items.set(feedResult.value.items);this.nextCursor.set(feedResult.value.nextCursor??null);}this.summary.set(summaryResult.status==='fulfilled'?summaryResult.value:null);}catch{if(revision===this.revision){this.profile.set(null);this.error.set(true);}}finally{if(revision===this.revision)this.loading.set(false);}}async loadMore():Promise<void>{const cursor=this.nextCursor();const profile=this.profile();const revision=this.revision;if(!cursor||!profile||this.loadingMore())return;this.loadingMore.set(true);try{const page=await this.api.invoke(getFeed,{kind:'Profile',profileId:profile.ownerId,limit:10,cursor});if(revision!==this.revision)return;this.items.update(items=>[...items,...page.items.filter(item=>!items.some(current=>current.content.id===item.content.id))]);this.nextCursor.set(page.nextCursor??null);}finally{if(revision===this.revision)this.loadingMore.set(false);}}}
