<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="..\Domain\ZosyalMedya.Modules.Moderation.Domain.csproj" /><ProjectReference Include="..\Contracts\ZosyalMedya.Modules.Moderation.Contracts.csproj" /><ProjectReference Include="..\..\..\BuildingBlocks\Application\ZosyalMedya.BuildingBlocks.Application.csproj" /><ProjectReference Include="..\..\Audit\Contracts\ZosyalMedya.Modules.Audit.Contracts.csproj" /><ProjectReference Include="..\..\Search\Contracts\ZosyalMedya.Modules.Search.Contracts.csproj" /></ItemGroup></Project>
