<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="..\Domain\ZosyalMedya.Modules.Search.Domain.csproj" /><ProjectReference Include="..\Contracts\ZosyalMedya.Modules.Search.Contracts.csproj" /><ProjectReference Include="..\..\..\BuildingBlocks\Application\ZosyalMedya.BuildingBlocks.Application.csproj" /><ProjectReference Include="..\..\SocialGraph\Contracts\ZosyalMedya.Modules.SocialGraph.Contracts.csproj" /></ItemGroup></Project>
