import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, effect, EffectRef, OnDestroy, OnInit, signal, viewChild } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Api, changeMessage, ConversationView, createConversation, getProfileByHandle, listConversations, listMessages, MessageView, ProfileView, SearchHit, sendMessage } from '@platform/api';
import { IonButton, IonButtons, IonContent, IonHeader, IonItem, IonLabel, IonList, IonNote, IonTextarea, IonTitle, IonToolbar } from '@ionic/angular/standalone';
import { MobileSession } from '../../core/auth/secure-token-storage';
import { MobileAuthorizedMediaGalleryComponent } from '../../core/media/mobile-authorized-media-gallery.component';
import { MobileMediaAttachmentPickerComponent } from '../../core/media/mobile-media-attachment-picker.component';
import { MobileMessagingRealtimeService } from '../../core/realtime/mobile-messaging-realtime.service';
import { MobileProfilePickerComponent } from '../../shared/mobile-profile-picker.component';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-mobile-messaging',
  imports: [ReactiveFormsModule, DatePipe, IonButton, IonButtons, IonContent, IonHeader, IonItem, IonLabel, IonList,
    IonNote, IonTextarea, IonTitle, IonToolbar, MobileProfilePickerComponent, MobileMediaAttachmentPickerComponent,
    MobileAuthorizedMediaGalleryComponent],
  template: `
    <ion-header translucent="true"><ion-toolbar>@if(selected()){<ion-buttons slot="start"><ion-button (click)="closeThread()">Geri</ion-button></ion-buttons>}<ion-title>{{selected()?participantLabel(selected()!):'Mesajlar'}}</ion-title></ion-toolbar></ion-header>
    <ion-content [fullscreen]="true">
      @if(!selected()){
        <div class="page-intro"><p>GÜVENLİ İLETİŞİM</p><h1>Konuşmalar.</h1><span>Her okuma ve gönderme işlemi sunucuda üyelik denetiminden geçer.</span></div>
        <form (ngSubmit)="startConversation()"><zm-mobile-profile-picker label="Mesaj göndereceğin kişiyi seç" hint="Ad veya kullanıcı adıyla gerçek bir profil ara." [excludeOwnerId]="actorId()" [initialSelection]="newRecipient()" (selectedChange)="chooseRecipient($event)"/><ion-button class="save" expand="block" type="submit" [disabled]="!newRecipient()||starting()">{{starting()?'Başlatılıyor…':'Yeni konuşma'}}</ion-button></form>
        <ion-list inset="true">@for(item of conversations();track item.id){<ion-item button="true" detail="true" (click)="select(item)"><ion-label><h2>{{participantLabel(item)}}</h2><p>{{item.updatedAtUtc|date:'dd MMM · HH:mm'}} · {{item.members.length}} üye</p></ion-label>@if(item.unreadCount){<ion-note slot="end" color="primary">{{item.unreadCount}}</ion-note>}</ion-item>}@empty{<ion-item><ion-label>Henüz konuşma yok.</ion-label></ion-item>}</ion-list>
      }@else{
        <div class="mobile-thread">@for(item of messages();track item.id){
          <article [class.mine]="item.senderId===actorId()" [class.deleted]="item.status==='Deleted'">
            @if(item.replyToId){<button class="reply-context" type="button" (click)="replyToId(item.replyToId)"><strong>Yanıt</strong><span>{{replyPreview(item.replyToId)}}</span></button>}
            @if(editingId()===item.id){<div class="mobile-edit"><ion-textarea [autoGrow]="true" maxlength="5000" [value]="editText()" (ionInput)="editText.set($any($event.detail).value??'')"/><span><ion-button fill="clear" size="small" (click)="cancelEdit()">Vazgeç</ion-button><ion-button size="small" [disabled]="!editText().trim()||changingId()===item.id" (click)="saveEdit(item)">Kaydet</ion-button></span></div>}
            @else{<span>{{item.status==='Deleted'?'Mesaj silindi':item.text}}</span>@if(item.status!=='Deleted'&&item.mediaIds.length){<zm-mobile-authorized-media-gallery [mediaIds]="item.mediaIds"/>}<footer><time>{{item.createdAtUtc|date:'HH:mm'}}@if(item.updatedAtUtc!==item.createdAtUtc&&item.status!=='Deleted'){ · düzenlendi}</time>@if(item.senderId===actorId()&&item.status!=='Deleted'){<small>{{deliveryLabel(item.deliveryState)}}</small>}</footer>@if(item.status!=='Deleted'){<nav><button type="button" (click)="replyTo(item)">Yanıtla</button>@if(item.senderId===actorId()&&canEdit(item)){<button type="button" (click)="beginEdit(item)">Düzenle</button>}@if(item.senderId===actorId()&&canDelete(item)){<button type="button" (click)="deleteMessage(item)">Herkesten sil</button>}</nav>}}
          </article>}@empty{<p>İlk mesajı gönder.</p>}</div>
        <div class="mobile-composer">@if(replyTarget();as reply){<div class="replying"><span><strong>Yanıtlanıyor</strong>{{reply.text||'Medya mesajı'}}</span><button type="button" [disabled]="sending()" (click)="cancelReply()">Kapat</button></div>}<zm-mobile-media-picker #messageMedia label="Mesaj eki" visibility="Private" [disabled]="sending()" (mediaIdsChange)="mediaIds.set($event)" (uploadingChange)="uploading.set($event)"/><form class="mobile-send" [formGroup]="composer" (ngSubmit)="send()"><ion-textarea formControlName="text" [autoGrow]="true" maxlength="5000" placeholder="Mesaj yaz"/><ion-button type="submit" [disabled]="cannotSend()">{{sending()?'Gönderiliyor…':'Gönder'}}</ion-button></form></div>
      }
      @if(message()){<ion-note class="status">{{message()}}</ion-note>}
    </ion-content>`,
  styles: [`
    .mobile-thread{min-height:calc(100% - 5.5rem);padding:max(5rem,env(safe-area-inset-top)) 1rem 13rem;display:flex;flex-direction:column;justify-content:flex-end;gap:.55rem}.mobile-thread article{align-self:flex-start;max-width:86%;background:var(--ion-item-background);border:1px solid var(--ion-border-color);padding:.65rem .8rem;border-radius:1rem 1rem 1rem .2rem}.mobile-thread article.mine{align-self:flex-end;background:var(--ion-color-primary);color:var(--ion-color-primary-contrast);border:0;border-radius:1rem 1rem .2rem 1rem}.mobile-thread article.deleted{color:var(--ion-color-medium);font-style:italic}.mobile-thread footer{display:flex;justify-content:flex-end;gap:.45rem;align-items:center}.mobile-thread time,.mobile-thread small{display:block;font-size:.62rem;opacity:.72;text-align:right;margin-top:.25rem}.mobile-thread nav{display:flex;justify-content:flex-end;gap:.25rem;margin-top:.25rem}.mobile-thread nav button,.reply-context,.replying button{min-height:36px;border:0;background:transparent;color:inherit;font-weight:700}.reply-context{display:grid;width:100%;padding:.3rem .45rem;border-left:3px solid currentColor;text-align:left}.reply-context span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;opacity:.72}.mobile-composer{position:sticky;bottom:0;background:var(--ion-background-color);border-top:1px solid var(--ion-border-color);padding:0 max(.6rem,env(safe-area-inset-right)) max(.5rem,env(safe-area-inset-bottom)) max(.6rem,env(safe-area-inset-left))}.mobile-send{display:flex;align-items:end}.mobile-send ion-textarea{--background:var(--ion-item-background);border-radius:1rem;padding:0 .5rem}.replying{display:flex;justify-content:space-between;align-items:center;border-left:3px solid var(--ion-color-primary);padding:.4rem .55rem;background:var(--ion-item-background)}.replying span{display:grid;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.replying strong{font-size:.68rem}.mobile-edit span{display:flex;justify-content:flex-end}.status{position:fixed;left:1rem;bottom:6rem;z-index:4}
  `,`
    .mobile-thread nav button,.reply-context,.replying button{min-height:44px}
    .mobile-send ion-textarea:focus-within,.mobile-edit ion-textarea:focus-within{outline:3px solid var(--ion-color-primary);outline-offset:2px}
  `],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class MobileMessagingPage implements OnInit, OnDestroy {
  readonly conversations=signal<ConversationView[]>([]);readonly selected=signal<ConversationView|null>(null);readonly messages=signal<MessageView[]>([]);readonly message=signal('');readonly sending=signal(false);readonly starting=signal(false);readonly actorId=signal('');readonly newRecipient=signal<SearchHit|null>(null);
  readonly mediaIds=signal<string[]>([]);readonly uploading=signal(false);readonly replyTarget=signal<MessageView|null>(null);readonly editingId=signal<string|null>(null);readonly editText=signal('');readonly changingId=signal<string|null>(null);
  readonly composer=new FormGroup({text:new FormControl('',{nonNullable:true})});readonly messageMedia=viewChild<MobileMediaAttachmentPickerComponent>('messageMedia');private unsubscribe?:()=>void;private receiptUnsubscribe?:()=>void;private changeUnsubscribe?:()=>void;private routeSubscription?:Subscription;private messageLoadRevision=0;private conversationLoadRevision=0;private queryRevision=0;private sendRevision=0;private currentSubject:string|null;private pendingConversationId:string|null=null;private readonly sessionSync:EffectRef;
  constructor(private readonly api:Api,private readonly realtime:MobileMessagingRealtimeService,private readonly session:MobileSession,private readonly route:ActivatedRoute){this.currentSubject=session.subject();this.actorId.set(this.currentSubject??'');this.sessionSync=effect(()=>{const subject=this.session.subject();if(subject===this.currentSubject)return;this.currentSubject=subject;++this.sendRevision;++this.messageLoadRevision;++this.conversationLoadRevision;this.sending.set(false);this.actorId.set(subject??'');this.conversations.set([]);this.selected.set(null);this.messages.set([]);this.mediaIds.set([]);this.replyTarget.set(null);this.composer.reset();void this.loadConversations();});}
  ngOnInit():void{this.routeSubscription=this.route.queryParamMap.subscribe(params=>{const revision=++this.queryRevision;const requestedConversation=params.get('conversation')?.trim()||null;this.pendingConversationId=requestedConversation;const handle=params.get('profil')?.trim()||'';this.newRecipient.set(null);if(handle||(requestedConversation&&requestedConversation!==this.selected()?.id))this.resetThreadForRecipientRoute();if(handle)void this.preselectRecipient(handle,revision);void this.loadConversations();});this.unsubscribe=this.realtime.onMessage(notice=>{void this.handleRealtimeMessage(notice.messageId,notice.conversationId);});this.receiptUnsubscribe=this.realtime.onReceipt?.(notice=>{if(this.selected()?.id===notice.conversationId)void this.loadMessages(notice.conversationId);});this.changeUnsubscribe=this.realtime.onChanged?.(changed=>{if(this.selected()?.id===changed.conversationId)this.replace(changed);});void this.realtime.connect().catch(()=>this.message.set('Çevrimdışı: geçmiş kullanılabilir.'));}ngOnDestroy():void{++this.sendRevision;this.sessionSync.destroy();this.routeSubscription?.unsubscribe();++this.queryRevision;++this.conversationLoadRevision;this.unsubscribe?.();this.receiptUnsubscribe?.();this.changeUnsubscribe?.();}
  async loadConversations():Promise<void>{const revision=++this.conversationLoadRevision;const subject=this.currentSubject;try{const items=(await this.api.invoke(listConversations,{limit:50})).items;if(revision!==this.conversationLoadRevision||subject!==this.currentSubject)return;this.conversations.set(items);const requested=this.pendingConversationId;if(requested){this.pendingConversationId=null;const match=items.find(item=>item.id===requested);if(match&&this.selected()?.id!==match.id)await this.select(match);else if(!match)this.message.set('Bu konuşma artık kullanılamıyor.');}}catch{if(revision===this.conversationLoadRevision&&subject===this.currentSubject)this.message.set('Konuşmalar yüklenemedi.');}}
  async select(item:ConversationView):Promise<void>{if(this.selected()?.id!==item.id)await this.messageMedia()?.discard();++this.messageLoadRevision;this.selected.set(item);this.replyTarget.set(null);this.cancelEdit();await this.loadMessages(item.id);await this.realtime.join(item.id).catch(()=>undefined);}async closeThread():Promise<void>{await this.messageMedia()?.discard();++this.messageLoadRevision;this.selected.set(null);this.messages.set([]);this.mediaIds.set([]);this.replyTarget.set(null);}
  async loadMessages(id:string):Promise<void>{const revision=++this.messageLoadRevision;try{const page=await this.api.invoke(listMessages,{conversationId:id,limit:100});if(revision!==this.messageLoadRevision||this.selected()?.id!==id)return;this.messages.set([...page.items].sort((a,b)=>Date.parse(a.createdAtUtc)-Date.parse(b.createdAtUtc)));}catch{if(revision===this.messageLoadRevision&&this.selected()?.id===id)this.message.set('Mesajlar yüklenemedi.');}}
  private async handleRealtimeMessage(messageId:string,conversationId:string):Promise<void>{try{await this.api.invoke(changeMessage,{messageId,body:{change:'Delivered',text:null}});}catch{ /* A later history read still records Read truthfully. */ }if(this.selected()?.id===conversationId)await this.loadMessages(conversationId);await this.loadConversations();}
  chooseRecipient(profile:SearchHit|null):void{this.newRecipient.set(profile);this.message.set('');}
  async startConversation():Promise<void>{const recipient=this.newRecipient();if(!recipient||this.starting())return;this.starting.set(true);try{const item=await this.api.invoke(createConversation,{body:{memberIds:[recipient.ownerId],title:null}});await this.loadConversations();await this.select(item);}catch{this.message.set('Konuşma başlatılamadı. Profilin mesaj izinlerini kontrol edebilirsin.');}finally{this.starting.set(false);}}
  async send():Promise<void>{const selected=this.selected();const text=this.composer.controls.text.value.trim();const picker=this.messageMedia();if(!selected||this.cannotSend())return;const reply=this.replyTarget();const ownerSubject=this.session.subject();const ownerAccessToken=this.session.accessToken();const operation=++this.sendRevision;const transfer=picker?.transfer()??{ids:[] as string[],discard:async()=>true,discardWithAccessToken:async()=>true,rollback:async()=>true};const now=new Date().toISOString();const optimistic:MessageView={id:crypto.randomUUID(),conversationId:selected.id,senderId:this.actorId(),text,mediaIds:transfer.ids,replyToId:reply?.id??null,status:'Sent',deliveryState:'Sent',createdAtUtc:now,updatedAtUtc:now,version:1};const before=this.messages();this.messages.update(items=>[...items,optimistic]);this.mediaIds.set([]);this.composer.reset();this.replyTarget.set(null);this.sending.set(true);try{const sent=await this.api.invoke(sendMessage,{conversationId:selected.id,body:{text,mediaIds:transfer.ids,replyToId:reply?.id??null}});if(operation===this.sendRevision&&ownerSubject===this.session.subject()&&this.selected()?.id===selected.id)this.messages.update(items=>items.map(item=>item.id===optimistic.id?sent:item));}catch(error){if(operation!==this.sendRevision||ownerSubject!==this.session.subject()){if(this.confirmedRejected(error))await transfer.discardWithAccessToken(ownerAccessToken);}else if(this.selected()?.id===selected.id){this.messages.set(before);await transfer.rollback();this.mediaIds.set(transfer.ids);this.composer.controls.text.setValue(text);this.replyTarget.set(reply);this.message.set('Mesaj gönderilemedi; metin, yanıt ve ekler korundu.');}else await transfer.discard();}finally{if(operation===this.sendRevision)this.sending.set(false);}}
  cannotSend():boolean{return this.sending()||this.uploading()||(!this.composer.controls.text.value.trim()&&!this.mediaIds().length);}
  replyTo(item:MessageView):void{this.replyTarget.set(item);}replyToId(id:string):void{const item=this.messages().find(value=>value.id===id);if(item)this.replyTo(item);}cancelReply():void{if(!this.sending())this.replyTarget.set(null);}replyPreview(id:string):string{const item=this.messages().find(value=>value.id===id);return item?.status==='Deleted'?'Silinmiş mesaj':item?.text||'Medya mesajı';}
  beginEdit(item:MessageView):void{this.editingId.set(item.id);this.editText.set(item.text);}cancelEdit():void{this.editingId.set(null);this.editText.set('');}
  async saveEdit(item:MessageView):Promise<void>{const text=this.editText().trim();if(!text||this.changingId())return;this.changingId.set(item.id);try{this.replace(await this.api.invoke(changeMessage,{messageId:item.id,body:{change:'Edit',text}}));this.cancelEdit();}catch{this.message.set('Mesaj düzenlenemedi.');}finally{this.changingId.set(null);}}
  async deleteMessage(item:MessageView):Promise<void>{if(this.changingId())return;this.changingId.set(item.id);try{this.replace(await this.api.invoke(changeMessage,{messageId:item.id,body:{change:'Delete',text:null}}));}catch{this.message.set('Mesaj silinemedi.');}finally{this.changingId.set(null);}}
  canEdit(item:MessageView):boolean{return Date.now()-Date.parse(item.createdAtUtc)<=15*60_000;}canDelete(item:MessageView):boolean{return Date.now()-Date.parse(item.createdAtUtc)<=24*60*60_000;}deliveryLabel(state:MessageView['deliveryState']):string{return state==='Read'?'Okundu':state==='Delivered'?'Teslim edildi':'Gönderildi';}
  participantLabel(item:ConversationView):string{if(item.kind==='Group')return item.title.trim()||'Grup konuşması';const other=item.members.find(member=>member.userId!==this.actorId());return other?.displayName?.trim()||'Doğrudan konuşma';}private replace(changed:MessageView):void{++this.messageLoadRevision;this.messages.update(items=>items.map(item=>item.id===changed.id&&changed.version>=item.version?changed:item));}
  private async preselectRecipient(handle:string,revision:number):Promise<void>{try{const profile=await this.api.invoke(getProfileByHandle,{handle});if(revision===this.queryRevision)this.newRecipient.set(this.profileHit(profile));}catch{if(revision===this.queryRevision)this.message.set('Bağlantıdaki profil seçilemedi; başka bir profil arayabilirsin.');}}
  private resetThreadForRecipientRoute():void{const picker=this.messageMedia();++this.messageLoadRevision;this.selected.set(null);this.messages.set([]);this.mediaIds.set([]);this.replyTarget.set(null);this.cancelEdit();this.composer.controls.text.reset();void picker?.discard();}
  private profileHit(profile:ProfileView):SearchHit{return{id:profile.id,ownerId:profile.ownerId,type:'Profile',title:profile.displayName,snippet:`@${profile.handle}`,deepLink:`/profil/${profile.handle}`,matchedTags:[],score:1};}
  private confirmedRejected(error:unknown):boolean{const status=(error as {status?:unknown})?.status;return typeof status==='number'&&status>=400&&status<500;}
}
