// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZosyalMedya.Modules.Messaging.Infrastructure.Persistence.PostgreSql;

#nullable disable

namespace ZosyalMedya.Modules.Messaging.Infrastructure.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    partial class MessagingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("messaging")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZosyalMedya.Modules.Messaging.Domain.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("conversations", "messaging");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Messaging.Domain.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid[]>("MediaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAtUtc");

                    b.ToTable("messages", "messaging");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Messaging.Domain.Conversations.Conversation", b =>
                {
                    b.OwnsMany("ZosyalMedya.Modules.Messaging.Domain.Conversations.ConversationMember", "_members", b1 =>
                        {
                            b1.Property<Guid>("ConversationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsArchived")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsPinned")
                                .HasColumnType("boolean");

                            b1.Property<DateTimeOffset>("JoinedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LeftAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("MutedUntilUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("ConversationId", "UserId");

                            b1.HasIndex("UserId", "LeftAtUtc");

                            b1.ToTable("conversation_members", "messaging");

                            b1.WithOwner()
                                .HasForeignKey("ConversationId");
                        });

                    b.Navigation("_members");
                });

            modelBuilder.Entity("ZosyalMedya.Modules.Messaging.Domain.Messages.Message", b =>
                {
                    b.OwnsMany("ZosyalMedya.Modules.Messaging.Domain.Messages.MessageReceipt", "_receipts", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeliveredAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("ReadAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("MessageId", "UserId");

                            b1.HasIndex("UserId", "ReadAtUtc");

                            b1.ToTable("message_receipts", "messaging");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.Navigation("_receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
