import { ChangeDetectionStrategy, Component, inject, OnDestroy, OnInit, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import {
  Api, changeCommunity, CommunityDetailView, CommunityMemberView, getCommunityBySlug,
  listCommunityMembers, setCommunityPin, setCommunityRules
} from '@platform/api';
import { DetailFailure, detailFailure } from './detail-state';
import { Subscription } from 'rxjs';
import { ReportActionComponent } from '../../core/moderation/report-action.component';
import { RichTextComponent } from '../../core/social/rich-text.component';

@Component({
  selector:'app-community-detail-page',imports:[RouterLink,ReportActionComponent,RichTextComponent],styleUrl:'./detail-page.css',changeDetection:ChangeDetectionStrategy.OnPush,
  template:`
    <a class="back-link" routerLink="/kesfet">← Keşfete dön</a>
    @if(loading()){<section class="state-panel" aria-busy="true"><strong>Topluluk hazırlanıyor.</strong><p>Görünür bilgiler ve kurallar yükleniyor.</p></section>}
    @else if(failure();as state){<section class="state-panel error" role="alert"><strong>{{state==='not-found'?'Topluluk bulunamadı.':state==='forbidden'?'Bu topluluk sana açık değil.':'Topluluk yüklenemedi.'}}</strong><p>{{state==='error'?'Bağlantını kontrol edip yeniden deneyebilirsin.':'Topluluk arşivlenmiş, gizlenmiş veya bağlantı değişmiş olabilir.'}}</p>@if(state==='error'){<button type="button" (click)="load()">Tekrar dene</button>}</section>}
    @else if(community();as item){
      <header class="detail-head"><p class="kicker">TOPLULUK</p><h1>{{item.name}}</h1><p class="lede"><zm-rich-text [text]="item.description" /></p></header>
      <article class="detail-card community-main"><div class="meta-row"><span class="audience">{{visibilityLabel(item.visibility)}}</span><span>{{item.activeMemberCount}} aktif üye</span>@if(item.viewerRole){<span>{{roleLabel(item.viewerRole)}}</span>}@else if(item.viewerMembershipStatus){<span>{{membershipLabel(item.viewerMembershipStatus)}}</span>}</div>
        @if(!item.viewerRole && (!item.viewerMembershipStatus || (item.viewerMembershipStatus==='Removed' && item.visibility==='Public'))){<div class="community-action"><button type="button" class="primary-action" (click)="requestMembership()" [disabled]="acting()">{{acting()?'İşleniyor…':item.visibility==='Public'?'Topluluğa katıl':'Üyelik isteği gönder'}}</button></div>}
        @if(item.viewerRole && item.viewerRole!=='Owner'){<div class="community-action"><button type="button" class="text-action danger" (click)="leave()" [disabled]="acting()">{{acting()?'İşleniyor…':'Topluluktan ayrıl'}}</button></div>}
        @if(actionMessage()){<p class="action-message" [class.error]="actionFailed()" [attr.role]="actionFailed()?'alert':'status'">{{actionMessage()}}</p>}
        <section class="rules"><h2>Topluluk kuralları</h2>@if(item.rules.length){<ol class="rule-list">@for(rule of item.rules;track $index){<li>{{rule}}</li>}</ol>}@else{<p class="quiet">Henüz yayımlanmış bir kural yok.</p>}</section>
        @if(canAdmin(item.viewerRole)){<section class="community-manage" aria-labelledby="rules-manage-title"><h2 id="rules-manage-title">Kuralları düzenle</h2><p class="quiet">Her satır ayrı bir kuraldır. En fazla 20 kural yayımlanabilir.</p><textarea aria-label="Topluluk kuralları" maxlength="6020" [value]="rulesDraft()" (input)="rulesDraft.set($any($event.target).value)"></textarea><button type="button" class="primary-action" (click)="saveRules()" [disabled]="acting()">Kuralları kaydet</button></section>}
        @if(item.pinnedContentIds.length){<section class="pins"><h2>Sabitlenen içerikler</h2><ul class="pin-list">@for(id of item.pinnedContentIds;track id){<li><a class="content-link" [routerLink]="['/icerik',id]">Sabitlenen gönderiyi aç</a>@if(canModerate(item.viewerRole)){<button type="button" class="text-action danger" (click)="unpin(id)" [disabled]="acting()">Sabitlemeyi kaldır</button>}</li>}</ul></section>}
        @if(canModerate(item.viewerRole)){<section class="member-manage" aria-labelledby="member-manage-title"><div class="section-heading"><div><h2 id="member-manage-title">Üyelik yönetimi</h2><p class="quiet">Bekleyen istekler yalnızca topluluk ekibine gösterilir.</p></div><button type="button" class="text-action" (click)="loadMembers(item.id)" [disabled]="membersLoading()">Yenile</button></div>@if(membersLoading()){<p role="status" class="quiet">Üyelik istekleri yükleniyor…</p>}@else if(membersError()){<p role="alert" class="action-message error">Üyelik istekleri yüklenemedi.</p>}@else if(pendingMembers().length){<ul class="member-list">@for(member of pendingMembers();track member.userId){<li><div>@if(member.handle){<a [routerLink]="['/profil',member.handle]"><strong>{{member.displayName}}</strong><span>&#64;{{member.handle}}</span></a>}@else{<strong>{{member.displayName}}</strong>}</div><button type="button" class="primary-action" (click)="approve(member)" [disabled]="acting()">Onayla</button></li>}</ul>}@else{<p class="quiet">Bekleyen üyelik isteği yok.</p>}</section>}
        <zm-report-action subjectType="Community" [subjectId]="item.id" label="Topluluğu bildir" />
      </article>
    }
  `
})
export class CommunityDetailPage implements OnInit,OnDestroy{
  readonly community=signal<CommunityDetailView|null>(null);readonly loading=signal(true);readonly failure=signal<DetailFailure|null>(null);readonly acting=signal(false);readonly actionMessage=signal('');readonly actionFailed=signal(false);private readonly route=inject(ActivatedRoute);private readonly api=inject(Api);private slug=this.route.snapshot.paramMap.get('slug')??'';
  readonly pendingMembers=signal<CommunityMemberView[]>([]);readonly membersLoading=signal(false);readonly membersError=signal(false);readonly rulesDraft=signal('');
  private memberLoadRevision=0;private detailLoadRevision=0;private routeSubscription?:Subscription;
  ngOnInit():void{this.routeSubscription=this.route.paramMap.subscribe(params=>{this.slug=params.get('slug')??'';++this.memberLoadRevision;this.pendingMembers.set([]);this.membersError.set(false);this.membersLoading.set(false);this.rulesDraft.set('');void this.load();});}
  ngOnDestroy():void{this.routeSubscription?.unsubscribe();++this.detailLoadRevision;++this.memberLoadRevision;}
  async load():Promise<void>{const revision=++this.detailLoadRevision;this.loading.set(true);this.failure.set(null);try{const item=await this.api.invoke(getCommunityBySlug,{slug:this.slug});if(revision!==this.detailLoadRevision)return;this.community.set(item);this.rulesDraft.set(item.rules.join('\n'));if(this.canModerate(item.viewerRole))await this.loadMembers(item.id);else this.pendingMembers.set([]);}catch(error){if(revision===this.detailLoadRevision){this.community.set(null);this.rulesDraft.set('');this.failure.set(detailFailure(error));}}finally{if(revision===this.detailLoadRevision)this.loading.set(false);}}
  visibilityLabel(value:string):string{return value==='Public'?'Herkese açık':value==='Private'?'Onaylı üyelik':'Gizli topluluk';}
  roleLabel(value:string):string{return ({Owner:'Topluluk sahibi',Administrator:'Yönetici',Moderator:'Moderatör',Member:'Üye'} as Record<string,string>)[value]??value;}
  membershipLabel(value:string):string{return ({Pending:'Üyelik isteği bekliyor',Invited:'Davet bekliyor',Removed:'Üyelik kaldırıldı'} as Record<string,string>)[value]??value;}
  canAdmin(role:string|null|undefined):boolean{return role==='Owner'||role==='Administrator';}
  canModerate(role:string|null|undefined):boolean{return this.canAdmin(role)||role==='Moderator';}
  async requestMembership():Promise<void>{const item=this.community();const canRequestAgain=item?.viewerMembershipStatus==='Removed'&&item.visibility==='Public';if(!item||this.acting()||item.viewerRole||(item.viewerMembershipStatus&&!canRequestAgain))return;this.acting.set(true);this.actionMessage.set('');this.actionFailed.set(false);try{await this.api.invoke(changeCommunity,{id:item.id,body:{change:'RequestMembership',targetId:null,reason:null}});await this.load();this.actionMessage.set(item.visibility==='Public'?'Topluluğa katıldın.':'Üyelik isteğin gönderildi.');}catch{this.actionMessage.set('Üyelik isteği gönderilemedi.');this.actionFailed.set(true);}finally{this.acting.set(false);}}
  async leave():Promise<void>{const item=this.community();if(!item||this.acting()||!item.viewerRole||item.viewerRole==='Owner'||!globalThis.confirm('Bu topluluktan ayrılmak istediğine emin misin?'))return;await this.runChange(()=>this.api.invoke(changeCommunity,{id:item.id,body:{change:'Leave',targetId:null,reason:null}}),'Topluluktan ayrıldın.');}
  async loadMembers(id:string):Promise<void>{const revision=++this.memberLoadRevision;this.membersLoading.set(true);this.membersError.set(false);try{const members=await this.api.invoke(listCommunityMembers,{id,status:'Pending',limit:50});if(revision===this.memberLoadRevision)this.pendingMembers.set(Array.isArray(members)?members:[]);}catch{if(revision===this.memberLoadRevision){this.pendingMembers.set([]);this.membersError.set(true);}}finally{if(revision===this.memberLoadRevision)this.membersLoading.set(false);}}
  async saveRules(value=this.rulesDraft()):Promise<void>{const item=this.community();if(!item||!this.canAdmin(item.viewerRole)||this.acting())return;const rules=value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(rules.length>20||rules.some(x=>x.length<2||x.length>300)){this.actionMessage.set('Kurallar 2–300 karakter olmalı ve en fazla 20 satır içermeli.');this.actionFailed.set(true);return;}await this.runChange(()=>this.api.invoke(setCommunityRules,{id:item.id,body:{rules}}),'Topluluk kuralları güncellendi.');}
  async unpin(contentId:string):Promise<void>{const item=this.community();if(!item||!this.canModerate(item.viewerRole)||this.acting())return;await this.runChange(()=>this.api.invoke(setCommunityPin,{id:item.id,contentId,pinned:false}),'İçerik sabitlemesi kaldırıldı.');}
  async approve(member:CommunityMemberView):Promise<void>{const item=this.community();if(!item||!this.canModerate(item.viewerRole)||this.acting())return;++this.memberLoadRevision;this.membersLoading.set(false);await this.runChange(()=>this.api.invoke(changeCommunity,{id:item.id,body:{change:'Approve',targetId:member.userId,reason:null}}),`${member.displayName} topluluğa kabul edildi.`);}
  private async runChange(action:()=>Promise<unknown>,success:string):Promise<void>{this.acting.set(true);this.actionMessage.set('');this.actionFailed.set(false);try{await action();await this.load();this.actionMessage.set(success);}catch{this.actionMessage.set('Topluluk işlemi tamamlanamadı; yetkini veya bağlantını kontrol et.');this.actionFailed.set(true);}finally{this.acting.set(false);}}
}
