import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { Api, block, follow, getMyProfile, getRelationship, mute, RelationshipView, SearchHit, unblock, unfollow, unmute } from '@platform/api';
import { ZmProfilePickerComponent } from '../profile/profile-picker.component';
import { SocialGraphPanelComponent } from './social-graph-panel.component';

@Component({selector:'app-connections-page',imports:[ZmProfilePickerComponent,SocialGraphPanelComponent],template:`<header><p class="kicker">İLİŞKİ KONTROLÜ</p><h1>Bağlantıların.</h1><p>Takip ağını, gelen özel hesap isteklerini ve seçtiğin bir profille ilişki durumunu gerçek verilerle yönet.</p></header>@if(viewerOwnerId();as ownerId){<zm-social-graph-panel [ownerId]="ownerId" />}@else if(viewerError()){<p class="message message-error" role="alert">Bağlantıların yüklenemedi. <button type="button" (click)="loadViewer()">Tekrar dene</button></p>}<div class="lookup"><zm-profile-picker label="Profil seç" hint="Takip, sessize alma veya engelleme durumunu görmek istediğin kişiyi ara." (selectedChange)="selectTarget($event)"></zm-profile-picker><button type="button" (click)="inspect()" [disabled]="!target()||loading()">{{loading()?'İnceleniyor…':'İncele'}}</button></div>@if(message()){<p class="message" [class.message-error]="messageIsError()" [attr.role]="messageIsError()?'alert':'status'">{{message()}}</p>}@if(state();as relation){<section class="relationship" aria-live="polite"><div class="state-word"><span>{{target()?.title}} İLE DURUM</span><strong>{{followStateLabel(relation.followState)}}</strong></div><dl><div><dt>Sessiz</dt><dd>{{relation.isMuted?'Evet':'Hayır'}}</dd></div><div><dt>Engelli</dt><dd>{{relation.isBlocked||relation.isBlockedByTarget?'Evet':'Hayır'}}</dd></div><div><dt>Yakın</dt><dd>{{relation.isCloseFriend?'Evet':'Hayır'}}</dd></div></dl><div class="actions">@if(relation.followState==='None'){<button (click)="act('follow')" [disabled]="loading()">Takip et</button>}@else{<button (click)="act('unfollow')" [disabled]="loading()">{{relation.followState==='Pending'?'İsteği geri çek':'Takibi bırak'}}</button>}<button (click)="act(relation.isMuted?'unmute':'mute')" [disabled]="loading()">{{relation.isMuted?'Sesi aç':'Sessize al'}}</button>@if(relation.isBlocked){<button class="danger" (click)="act('unblock')" [disabled]="loading()">Engeli kaldır</button>}@else if(confirmingBlock()){<button class="danger" (click)="act('block')" [disabled]="loading()">Engellemeyi onayla</button><button (click)="cancelBlock()" [disabled]="loading()">Vazgeç</button>}@else{<button class="danger" (click)="requestBlock()" [disabled]="loading()">Engelle</button>}</div>@if(confirmingBlock()){<p class="block-warning" role="alert">Engellemek; karşılıklı takibi sonlandırır ve bu profilin seninle etkileşimini sınırlar. Devam etmek için işlemi onayla.</p>}</section>}`,
styleUrl:'./connections.page.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class ConnectionsPage{
  readonly target=signal<SearchHit|null>(null);readonly state=signal<RelationshipView|null>(null);readonly message=signal('');readonly messageIsError=signal(false);readonly loading=signal(false);readonly confirmingBlock=signal(false);
  readonly viewerOwnerId=signal<string|null>(null);readonly viewerError=signal(false);
  constructor(private readonly api:Api){void this.loadViewer();}
  async loadViewer():Promise<void>{this.viewerError.set(false);try{this.viewerOwnerId.set((await this.api.invoke(getMyProfile,{})).ownerId);}catch{this.viewerError.set(true);}}
  selectTarget(profile:SearchHit|null):void{this.target.set(profile);this.state.set(null);this.message.set('');this.messageIsError.set(false);this.confirmingBlock.set(false);}
  async inspect():Promise<void>{const target=this.target();if(!target||this.loading())return;this.loading.set(true);this.messageIsError.set(false);try{this.state.set(await this.api.invoke(getRelationship,{targetId:target.ownerId}));this.message.set('');}catch{this.message.set('İlişki bilgisi alınamadı.');this.messageIsError.set(true);}finally{this.loading.set(false);}}
  requestBlock():void{this.confirmingBlock.set(true);}
  cancelBlock():void{this.confirmingBlock.set(false);}
  async act(action:'follow'|'unfollow'|'mute'|'unmute'|'block'|'unblock'):Promise<void>{const target=this.target();if(!target||this.loading())return;const fn={follow,unfollow,mute,unmute,block,unblock}[action];this.loading.set(true);this.messageIsError.set(false);try{this.state.set(await this.api.invoke(fn,{targetId:target.ownerId}));this.confirmingBlock.set(false);this.message.set('Durum güncellendi.');}catch{this.message.set('Bu işlem ilişki politikası nedeniyle uygulanamadı.');this.messageIsError.set(true);}finally{this.loading.set(false);}}
  followStateLabel(state:RelationshipView['followState']):string{return ({None:'Takip edilmiyor',Pending:'İstek bekliyor',Following:'Takip ediliyor'} as const)[state];}
}
