import { TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { Api, acceptFollow, getSocialGraphSummary, listIncomingFollowRequests, listSocialGraphProfiles, SocialGraphProfileView } from '@platform/api';
import { describe,expect,it,vi } from 'vitest';
import { MediaResolver } from '../../core/media/media-resolver.service';
import { SocialGraphPanelComponent } from './social-graph-panel.component';

describe('SocialGraphPanelComponent',()=>{
  it('loads real counts and paged profiles without per-row profile requests',async()=>{const invoke=vi.fn(async(operation:unknown)=>operation===getSocialGraphSummary?{ownerId:'owner',followerCount:2,followingCount:1,pendingRequestCount:1,canManageRequests:true}:operation===listSocialGraphProfiles?{items:[{ownerId:'person',handle:'ayse',displayName:'Ayşe',profileMediaId:null,isVerified:true}],nextCursor:null}:{items:[],nextCursor:null});await TestBed.configureTestingModule({imports:[SocialGraphPanelComponent],providers:[provideRouter([]),{provide:Api,useValue:{invoke}},{provide:MediaResolver,useValue:{resolve:vi.fn().mockRejectedValue(new Error('none'))}}]}).compileComponents();const fixture=TestBed.createComponent(SocialGraphPanelComponent);fixture.componentRef.setInput('ownerId','owner');fixture.detectChanges();await fixture.whenStable();fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('2');expect(fixture.nativeElement.textContent).toContain('Ayşe');expect(invoke).toHaveBeenCalledWith(listSocialGraphProfiles,{ownerId:'owner',kind:'Followers',limit:20,cursor:undefined});});
  it('accepts an incoming request and updates the visible counts',async()=>{const request={ownerId:'requester',handle:'istek',displayName:'İstek Sahibi',profileMediaId:null,isVerified:false};const invoke=vi.fn(async(operation:unknown)=>operation===getSocialGraphSummary?{ownerId:'owner',followerCount:0,followingCount:0,pendingRequestCount:1,canManageRequests:true}:operation===listSocialGraphProfiles?{items:[],nextCursor:null}:operation===listIncomingFollowRequests?{items:[request],nextCursor:null}:operation===acceptFollow?{}:null);await TestBed.configureTestingModule({imports:[SocialGraphPanelComponent],providers:[provideRouter([]),{provide:Api,useValue:{invoke}},{provide:MediaResolver,useValue:{resolve:vi.fn().mockRejectedValue(new Error('none'))}}]}).compileComponents();const fixture=TestBed.createComponent(SocialGraphPanelComponent);fixture.componentRef.setInput('ownerId','owner');fixture.detectChanges();await fixture.whenStable();fixture.componentInstance.select('Requests');await fixture.whenStable();fixture.detectChanges();await fixture.componentInstance.decide(request,true);expect(invoke).toHaveBeenCalledWith(acceptFollow,{requesterId:'requester'});expect(fixture.componentInstance.items()).toEqual([]);expect(fixture.componentInstance.summary()?.pendingRequestCount).toBe(0);expect(fixture.componentInstance.summary()?.followerCount).toBe(1);});
  it('keeps the newly selected tab responsive when an older request finishes later',async()=>{let releaseFollowers!:(value:{items:SocialGraphProfileView[];nextCursor:null})=>void;const followers=new Promise<{items:SocialGraphProfileView[];nextCursor:null}>(resolve=>releaseFollowers=resolve);const following:SocialGraphProfileView={ownerId:'following',handle:'takip',displayName:'Takip Edilen',profileMediaId:null,isVerified:false};const invoke=vi.fn(async(operation:unknown,params?:{kind?:string})=>operation===getSocialGraphSummary?{ownerId:'owner',followerCount:1,followingCount:1,pendingRequestCount:0,canManageRequests:false}:operation===listSocialGraphProfiles&&params?.kind==='Followers'?followers:{items:[following],nextCursor:null});await TestBed.configureTestingModule({imports:[SocialGraphPanelComponent],providers:[provideRouter([]),{provide:Api,useValue:{invoke}},{provide:MediaResolver,useValue:{resolve:vi.fn().mockRejectedValue(new Error('none'))}}]}).compileComponents();const fixture=TestBed.createComponent(SocialGraphPanelComponent);fixture.componentRef.setInput('ownerId','owner');fixture.detectChanges();await Promise.resolve();await Promise.resolve();fixture.componentInstance.select('Following');await Promise.resolve();await Promise.resolve();expect(fixture.componentInstance.items()).toEqual([following]);releaseFollowers({items:[],nextCursor:null});await fixture.whenStable();expect(fixture.componentInstance.items()).toEqual([following]);expect(fixture.componentInstance.listLoading()).toBe(false);});
  it('opens the actionable request queue when requested by a notification deep link',async()=>{const invoke=vi.fn(async(operation:unknown)=>operation===getSocialGraphSummary?{ownerId:'owner',followerCount:0,followingCount:0,pendingRequestCount:0,canManageRequests:true}:operation===listIncomingFollowRequests?{items:[],nextCursor:null}:{items:[],nextCursor:null});await TestBed.configureTestingModule({imports:[SocialGraphPanelComponent],providers:[provideRouter([]),{provide:Api,useValue:{invoke}},{provide:MediaResolver,useValue:{resolve:vi.fn()}}]}).compileComponents();const fixture=TestBed.createComponent(SocialGraphPanelComponent);fixture.componentRef.setInput('ownerId','owner');fixture.componentRef.setInput('initialKind','Requests');fixture.detectChanges();await fixture.whenStable();expect(fixture.componentInstance.kind()).toBe('Requests');expect(invoke).toHaveBeenCalledWith(listIncomingFollowRequests,{limit:20,cursor:undefined});});
  it('ignores a delayed request decision after the panel owner changes',async()=>{let release!:(value:unknown)=>void;const decision=new Promise(resolve=>release=resolve);const requestA={ownerId:'requester-a',handle:'a',displayName:'A',profileMediaId:null,isVerified:false};const requestB={ownerId:'requester-b',handle:'b',displayName:'B',profileMediaId:null,isVerified:false};let lists=0;const invoke=vi.fn((operation:unknown,params?:{ownerId?:string})=>operation===getSocialGraphSummary?Promise.resolve({ownerId:params?.ownerId??'',followerCount:0,followingCount:0,pendingRequestCount:1,canManageRequests:true}):operation===listIncomingFollowRequests?Promise.resolve({items:[++lists===1?requestA:requestB],nextCursor:null}):operation===acceptFollow?decision:Promise.resolve({items:[],nextCursor:null}));await TestBed.configureTestingModule({imports:[SocialGraphPanelComponent],providers:[provideRouter([]),{provide:Api,useValue:{invoke}},{provide:MediaResolver,useValue:{resolve:vi.fn()}}]}).compileComponents();const fixture=TestBed.createComponent(SocialGraphPanelComponent);fixture.componentRef.setInput('ownerId','owner-a');fixture.componentRef.setInput('initialKind','Requests');fixture.detectChanges();await fixture.whenStable();const pending=fixture.componentInstance.decide(requestA,true);fixture.componentRef.setInput('ownerId','owner-b');fixture.detectChanges();await fixture.whenStable();release({});await pending;expect(fixture.componentInstance.items()).toEqual([requestB]);expect(fixture.componentInstance.summary()?.followerCount).toBe(0);expect(fixture.componentInstance.actionMessage()).toBe('');});
});
