import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { IonButton, IonContent, IonHeader, IonInput, IonItem, IonLabel, IonList, IonNote, IonTitle, IonToolbar } from '@ionic/angular/standalone';
import { Api, MfaEnrollment, SessionView, beginMfaEnrollment, confirmMfaEnrollment, deleteMyIdentityData, disableMfa, exportMyIdentityData, listSessions, revokeSession } from '@platform/api';
import { MobileSession } from '../../core/auth/secure-token-storage';

@Component({
  selector:'app-mobile-settings',
  imports:[ReactiveFormsModule,IonButton,IonContent,IonHeader,IonInput,IonItem,IonLabel,IonList,IonNote,IonTitle,IonToolbar],
  template:`<ion-header translucent="true"><ion-toolbar><ion-title>Güvenlik ve gizlilik</ion-title></ion-toolbar></ion-header><ion-content [fullscreen]="true"><div class="page-intro"><p>HESAP KONTROLÜ</p><h1>Güvende kal.</h1><span>Cihazlarını, ikinci faktörü ve kişisel verilerini yönet.</span></div>@if(message()){<ion-note class="status">{{message()}}</ion-note>}
  <ion-list inset="true"><ion-item lines="full"><ion-label><h2>Etkin cihazlar</h2><p>Tanımadığın oturumları iptal et.</p></ion-label></ion-item>@for(item of sessions();track item.id){<ion-item><ion-label><h3>{{item.deviceName}}</h3><p>{{item.lastUsedAtUtc}} · {{item.isRevoked?'İptal edildi':'Etkin'}}</p></ion-label>@if(!item.isRevoked){<ion-button fill="outline" (click)="revoke(item)">İptal</ion-button>}</ion-item>}</ion-list>
  <ion-list inset="true"><ion-item lines="full"><ion-label><h2>İkinci faktör</h2><p>TOTP doğrulayıcı uygulaması kullan.</p></ion-label></ion-item>@if(!enrollment()){<ion-button expand="block" (click)="beginMfa()">MFA kurulumu başlat</ion-button>}@else{<ion-item><ion-label class="ion-text-wrap"><h3>Kurulum anahtarı</h3><p>{{enrollment()!.secret}}</p></ion-label></ion-item><form [formGroup]="confirmForm" (ngSubmit)="confirmMfa()"><ion-item><ion-input label="Altı haneli kod" labelPlacement="stacked" formControlName="code" inputmode="numeric"></ion-input></ion-item><ion-button expand="block" type="submit" [disabled]="confirmForm.invalid">Etkinleştir</ion-button></form>}<form [formGroup]="disableForm" (ngSubmit)="turnOffMfa()"><ion-item><ion-input label="MFA veya kurtarma kodu" labelPlacement="stacked" formControlName="code"></ion-input></ion-item><ion-button expand="block" fill="outline" type="submit" [disabled]="disableForm.invalid">MFA'yı kapat</ion-button></form>@if(recoveryCodes().length){<ion-item><ion-label class="ion-text-wrap"><h3>Kurtarma kodlarını güvenli sakla</h3>@for(code of recoveryCodes();track code){<p>{{code}}</p>}</ion-label></ion-item>}</ion-list>
  <ion-list inset="true"><ion-item><ion-label><h2>Verilerimi dışa aktar</h2><p>Kimlik ve oturum verilerini JSON olarak al.</p></ion-label><ion-button fill="outline" (click)="exportData()">Hazırla</ion-button></ion-item></ion-list>
  <ion-list inset="true"><ion-item color="danger"><ion-label><h2>Hesabı sil</h2><p>Bu işlem geri alınamaz.</p></ion-label></ion-item><form [formGroup]="deleteForm" (ngSubmit)="deleteAccount()"><ion-item><ion-input label="Mevcut parola" labelPlacement="stacked" type="password" formControlName="password"></ion-input></ion-item><ion-item><ion-input label="MFA etkinse kod" labelPlacement="stacked" formControlName="mfaCode"></ion-input></ion-item><ion-item><ion-input label="Onaylamak için SİL yaz" labelPlacement="stacked" formControlName="confirmation"></ion-input></ion-item><ion-button color="danger" expand="block" type="submit" [disabled]="deleteForm.invalid||deleteForm.controls.confirmation.value!=='SİL'">Hesabımı sil</ion-button></form></ion-list></ion-content>`,
  styles:[`.status{display:block;margin:12px 20px}.page-intro{padding:28px 22px 8px}.page-intro p{letter-spacing:.16em;font-size:.68rem}.page-intro h1{font-family:Georgia,serif;font-size:2.5rem;margin:.3rem 0}.page-intro span{color:var(--ion-color-medium)}ion-list{margin-bottom:18px}ion-button[expand=block]{margin:12px}`],
  changeDetection:ChangeDetectionStrategy.OnPush
})
export class MobileSettingsPage implements OnInit{
  readonly sessions=signal<SessionView[]>([]);readonly enrollment=signal<MfaEnrollment|null>(null);readonly recoveryCodes=signal<string[]>([]);readonly message=signal('');
  readonly confirmForm=new FormGroup({code:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(6)]})});readonly disableForm=new FormGroup({code:new FormControl('',{nonNullable:true,validators:[Validators.required]})});readonly deleteForm=new FormGroup({password:new FormControl('',{nonNullable:true,validators:[Validators.required]}),mfaCode:new FormControl('',{nonNullable:true}),confirmation:new FormControl('',{nonNullable:true,validators:[Validators.required]})});
  constructor(private readonly api:Api,private readonly session:MobileSession,private readonly router:Router){}ngOnInit():void{void this.load();}
  async load():Promise<void>{try{this.sessions.set(await this.api.invoke(listSessions));}catch{this.message.set('Oturumlar yüklenemedi.');}}
  async revoke(item:SessionView):Promise<void>{try{await this.api.invoke(revokeSession,{sessionId:item.id});await this.load();this.message.set('Oturum iptal edildi.');}catch{this.message.set('Oturum iptal edilemedi.');}}
  async beginMfa():Promise<void>{try{this.enrollment.set(await this.api.invoke(beginMfaEnrollment));}catch{this.message.set('MFA kurulumu başlatılamadı.');}}
  async confirmMfa():Promise<void>{if(this.confirmForm.invalid||!this.enrollment())return;try{const result=await this.api.invoke(confirmMfaEnrollment,{body:{enrollmentToken:this.enrollment()!.enrollmentToken,code:this.confirmForm.controls.code.value}});this.recoveryCodes.set(result.recoveryCodes);this.enrollment.set(null);this.message.set('MFA etkinleştirildi.');}catch{this.message.set('Kod doğrulanamadı.');}}
  async turnOffMfa():Promise<void>{if(this.disableForm.invalid)return;try{await this.api.invoke(disableMfa,{body:{code:this.disableForm.controls.code.value}});this.disableForm.reset();this.message.set('MFA kapatıldı.');}catch{this.message.set('Kod doğrulanamadı.');}}
  async exportData():Promise<void>{try{const data=await this.api.invoke(exportMyIdentityData);const text=JSON.stringify(data,null,2);if(navigator.share)await navigator.share({title:'Hesap verilerim',text});else await navigator.clipboard.writeText(text);this.message.set('Dışa aktarma paylaşım için hazır.');}catch{this.message.set('Dışa aktarma hazırlanamadı.');}}
  async deleteAccount():Promise<void>{if(this.deleteForm.invalid||this.deleteForm.controls.confirmation.value!=='SİL')return;const value=this.deleteForm.getRawValue();try{await this.api.invoke(deleteMyIdentityData,{body:{currentPassword:value.password,mfaCode:value.mfaCode||null}});this.session.clear();await this.router.navigateByUrl('/giris');}catch{this.message.set('Hesap silinemedi; bilgileri kontrol et.');}}
}
