import { ChangeDetectionStrategy, Component, effect, inject, input, signal } from '@angular/core';
import { Api, CreateModerationReportRequest, createModerationReport } from '@platform/api';

type SubjectType=CreateModerationReportRequest['subjectType'];type Reason=CreateModerationReportRequest['reason'];

@Component({
  selector:'zm-report-action',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,
  styles:[`:host{display:block;margin-top:var(--zm-space-4)}details{border-top:1px solid var(--zm-border-subtle);padding-top:var(--zm-space-3)}summary{width:max-content;color:var(--zm-text-3);font-size:var(--zm-text-sm);font-weight:750;cursor:pointer}form{display:grid;gap:var(--zm-space-3);max-width:36rem;margin-top:var(--zm-space-3);padding:var(--zm-space-4);border-inline-start:3px solid var(--zm-warning);background:var(--zm-surface-1)}label{display:grid;gap:var(--zm-space-1);color:var(--zm-text-2);font-size:var(--zm-text-sm)}select,textarea{min-height:var(--zm-input-min-height);border:1px solid var(--zm-input-border);border-radius:var(--zm-input-radius);background:var(--zm-input-bg);color:var(--zm-input-fg);padding:var(--zm-input-padding-y) var(--zm-input-padding-x);font:inherit}textarea{min-height:6rem;resize:vertical}button{width:max-content;min-height:var(--zm-button-min-height);border:1px solid var(--zm-button-secondary-border);border-radius:var(--zm-button-radius);background:var(--zm-button-secondary-bg);color:var(--zm-button-secondary-fg);padding:var(--zm-button-padding-y) var(--zm-button-padding-x);font-weight:800;cursor:pointer}button:disabled{cursor:wait;opacity:.65}select:focus-visible,textarea:focus-visible,button:focus-visible,summary:focus-visible{outline:var(--zm-focus-ring-width) solid var(--zm-focus);outline-offset:var(--zm-focus-ring-offset)}.status{margin:0;color:var(--zm-success)}.status.error{color:var(--zm-danger)}`],
  template:`<details [open]="open()" (toggle)="open.set($any($event.target).open)"><summary>{{label()}}</summary>@if(open()){<form (submit)="submit($event)"><label>Neden<select [value]="reason()" (change)="reason.set($any($event.target).value)">@for(option of reasons;track option.value){<option [value]="option.value">{{option.label}}</option>}</select></label><label>Açıklama<textarea maxlength="2000" [value]="details()" (input)="details.set($any($event.target).value)" placeholder="Neyi ve neden bildirdiğini açıkla"></textarea></label><button type="submit" [disabled]="sending()||details().trim().length<5">{{sending()?'Gönderiliyor…':'Raporu gönder'}}</button>@if(message()){<p class="status" [class.error]="failed()" [attr.role]="failed()?'alert':'status'">{{message()}}</p>}</form>}</details>`
})
export class ReportActionComponent{
  readonly subjectType=input.required<SubjectType>();readonly subjectId=input.required<string>();readonly label=input('Bildir');
  readonly open=signal(false);readonly reason=signal<Reason>('Other');readonly details=signal('');readonly sending=signal(false);readonly message=signal('');readonly failed=signal(false);
  readonly reasons:{value:Reason;label:string}[]=[{value:'Spam',label:'Spam'},{value:'Harassment',label:'Taciz'},{value:'Hate',label:'Nefret söylemi'},{value:'Violence',label:'Şiddet'},{value:'SexualContent',label:'Cinsel içerik'},{value:'Impersonation',label:'Taklit'},{value:'Privacy',label:'Gizlilik'},{value:'Misinformation',label:'Yanlış bilgi'},{value:'Other',label:'Diğer'}];
  private readonly api=inject(Api);
  private subjectRevision=0;
  constructor(){effect(()=>{this.subjectType();this.subjectId();this.subjectRevision++;this.open.set(false);this.reason.set('Other');this.details.set('');this.sending.set(false);this.message.set('');this.failed.set(false);});}
  async submit(event:Event):Promise<void>{event.preventDefault();const details=this.details().trim();if(details.length<5||this.sending())return;const revision=this.subjectRevision;const subjectType=this.subjectType();const subjectId=this.subjectId();const reason=this.reason();this.sending.set(true);this.message.set('');this.failed.set(false);try{await this.api.invoke(createModerationReport,{body:{subjectType,subjectId,reason,details,evidenceReferences:[]}});if(revision!==this.subjectRevision)return;this.details.set('');this.message.set('Rapor güvenle alındı.');}catch{if(revision!==this.subjectRevision)return;this.message.set('Rapor gönderilemedi veya bu hedef için açık bir raporun var.');this.failed.set(true);}finally{if(revision===this.subjectRevision)this.sending.set(false);}}
}
