import { ChangeDetectionStrategy,Component,signal } from '@angular/core';
import { FormControl,FormGroup,ReactiveFormsModule,Validators } from '@angular/forms';
import { Router,RouterLink } from '@angular/router';
import { IonButton,IonContent,IonInput,IonItem,IonLabel,IonNote,IonSpinner } from '@ionic/angular/standalone';
import { MobileAuthService } from '../../core/auth/mobile-auth.service';

@Component({selector:'app-mobile-login',imports:[ReactiveFormsModule,RouterLink,IonButton,IonContent,IonInput,IonItem,IonLabel,IonNote,IonSpinner],template:`<ion-content [fullscreen]="true" class="auth-page"><main class="auth-stage"><header><span class="brand">ENTERPRISE SOCIAL<span>•</span></span><p>SAKİN BİR PAYLAŞIM ALANI</p><h1>{{registerMode()?'Alanını kur.':'Yeniden merhaba.'}}</h1><p class="lead">Çevreni seç, profilini kendi ritminde şekillendir.</p></header><form [formGroup]="form" (ngSubmit)="submit()">@if(registerMode()){<ion-item lines="none"><ion-label position="stacked">E-posta</ion-label><ion-input formControlName="email" type="email" autocomplete="email"></ion-input></ion-item>}<ion-item lines="none"><ion-label position="stacked">Kullanıcı adı veya e-posta</ion-label><ion-input formControlName="login" autocomplete="username"></ion-input></ion-item><ion-item lines="none"><ion-label position="stacked">Parola</ion-label><ion-input formControlName="password" type="password" autocomplete="current-password"></ion-input></ion-item>@if(!registerMode()){<ion-item lines="none"><ion-label position="stacked">MFA veya kurtarma kodu</ion-label><ion-input formControlName="mfaCode" autocomplete="one-time-code"></ion-input></ion-item>}@if(error()){<ion-note color="danger" role="alert">{{error()}}</ion-note>}<ion-button expand="block" type="submit" [disabled]="form.invalid||busy()">@if(busy()){<ion-spinner name="crescent"></ion-spinner>}@else{{{registerMode()?'Hesap oluştur':'Giriş yap'}}}</ion-button></form><ion-button fill="clear" expand="block" (click)="toggle()">{{registerMode()?'Hesabım var':'Yeni hesap oluştur'}}</ion-button><ion-button fill="clear" expand="block" routerLink="/auth/reset-password">Parolamı unuttum</ion-button></main></ion-content>`,changeDetection:ChangeDetectionStrategy.OnPush})
export class MobileLoginPage{
  readonly registerMode=signal(false);readonly busy=signal(false);readonly error=signal('');
  readonly form=new FormGroup({login:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(3)]}),email:new FormControl('',{nonNullable:true,validators:[Validators.email]}),password:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(12)]}),mfaCode:new FormControl('',{nonNullable:true})});
  constructor(private readonly auth:MobileAuthService,private readonly router:Router){}
  toggle():void{this.registerMode.update(value=>!value);this.error.set('');}
  async submit():Promise<void>{if(this.form.invalid)return;this.busy.set(true);this.error.set('');try{const value=this.form.getRawValue();if(this.registerMode()){if(!value.email){this.error.set('E-posta gerekli.');return;}await this.auth.register(value.login,value.email,value.password);this.error.set('Doğrulama bağlantısı e-posta kutuna gönderildi.');this.registerMode.set(false);this.form.controls.login.setValue(value.email);}else{await this.auth.login(value.login,value.password,value.mfaCode);await this.router.navigateByUrl('/profil');}}catch{this.error.set('Bilgiler doğrulanamadı. Lütfen yeniden dene.');}finally{this.busy.set(false);}}
}
